Improve mime type filtering
10up/ElasticPress pull request #1887
Opened 2020-09-10 17:00 UTC by roborourke

### Description of the Change

As noted in issue #1604 the image block sends a mime type value of `image` through as an array which goes against the convention this part of the query filter relied on. This update makes the filter more agnostic, working with a single string (as `wp_post_mime_type_where()` does) or an array, plus it will then separate the values into full terms and prefixes.

### Alternate Designs

### Benefits

This has the benefit of supporting almost any combination of values given in the `post_mime_type` argument and avoids the use of a `regexp` query which can be slower to run.

This fixes issue #1604

### Possible Drawbacks

### Verification Process

Searching media in the media modal opened from an image block in the block editor now returns results.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues

- #1604 

### Changelog Entry

- Changed `post_mime_type` filtering to support more edge cases

2020-09-10 17:01 UTC, roborourke commented
I'll look into updating the tests too, just wanted to get this up.

2020-09-16 10:41 UTC, roborourke commented
Ah seems the test suite is a bit broken right now.

2020-10-07 23:43 UTC, tlovett1 requested changes

2020-10-07 23:43 UTC, tlovett1 commented on includes/classes/Indexable/Post/Post.php
> +			} else {
This doesn't make total sense to me. I think it would be better to check if it's a string, then check if it's an array. If it's anything else, ignore the parameter.

2020-10-07 23:43 UTC, tlovett1 commented on includes/classes/Indexable/Post/Post.php
> +							'post_mime_type' => $prefix,
Is mime type supposed to support wildcards?

2020-10-08 08:26 UTC, roborourke commented on includes/classes/Indexable/Post/Post.php
> +							'post_mime_type' => $prefix,
Yeah but only in a limited way - this function is used to build the SQL in WP core https://developer.wordpress.org/reference/functions/wp_post_mime_type_where/

You can query by subgroup eg. `image` or by fully qualified mime types like `image/jpeg`

2020-10-08 08:28 UTC, roborourke commented on includes/classes/Indexable/Post/Post.php
> +			} else {
Yep, good shout 👍

2021-06-14 18:20 UTC, felipeelia commented
Closing this as we've merged #2222 to fix the same issue.

2021-06-14 18:20 UTC, closed without merging