Feature: Dynamic index
10up/ElasticPress pull request #1949
Opened 2020-11-03 17:32 UTC by dinhtungdu

### Description of the Change
This PR adds a basic algorithm is to increase/decrease the number of posts/documents while indexing by timing each request. This also fixes the issue with very large documents (over 100MB) which exceed the `max_content_length` of Elasticsearch.

### Alternate Designs
n/a

### Benefits
A more reliable sync process that can self-tune base on the network and hardward condition at the sync time.

### Possible Drawbacks
None that I'm aware of.

### Verification Process
- Set bulk index setting to `1` and run sync. Check the setting value after the sync, see it changed.
- Upload some large documents then turn on document indexing. Run a sync, see the index succeeds.

### Checklist:

- [ ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues

### Changelog Entry

2020-11-10 16:54 UTC, brandwaffle commented
@dinhtungdu This is looking great! For release, we'd like to have the Settings menu display the current number of posts indexing per cycle using Dynamic Indexing. Then we'd like another field where someone can "override" the value and set it to a certain number per index cycle (i.e. what happens today). This is so someone can set a value in case there is a reason not to use dynamic indexing.

2020-11-19 09:58 UTC, dinhtungdu commented
@brandwaffle I add a checkbox to toggle the dynamic index feature.

When the box is checked. The value of the bulk setting will change dynamically. I decided to keep that behavior because:
- I don't want to add more data to the database.
- Site admins have a way to know the current bulk setting value set by the algorithm.

When the checkbox is unchecked (which is the default setting), ElasticPress will use the bulk setting as before.

For both scenarios, an improvement introduced in this PR is applied. EP will send only requests which are less than 100MB, and continue where it left off in the next index cycle. 100MB is is the default value of ES `[max_content_length](https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-http.html#_http_settings)` and this is filterable by `ep_max_content_length`.

2021-06-08 17:20 UTC, Rahmon commented
Hi @dinhtungdu 

I started to review this PR and seems the dynamic index is working but when I tried to index a document I got an error. 

Also, I've updated the PR, could you check if everything is still working?

2021-06-08 17:34 UTC, felipeelia requested changes

2021-06-08 17:34 UTC, felipeelia commented on includes/partials/settings-page.php
> +						<legend class="description">Enabling this setting let ElasticPress adjust the bulk index setting automatically for a more reliable and optimized index process.</legend>
@dinhtungdu @Rahmon let's use an i18n function like `esc_html_e()` here please.

2021-06-08 17:35 UTC, felipeelia commented
@Rahmon @dinhtungdu not sure if this is something already under your radars, but before we merge this one, let's make sure to add all `@since` tags we need, okay? Thanks!

2021-06-10 06:42 UTC, dinhtungdu commented
@Rahmon Are you getting memory limit fatal error? If yes, please increase your PHP memory_limit setting. For large documents, we need a high limit because of the encoding process. I can index 100MB documents with memory_limit set to 512M.

2021-06-10 06:50 UTC, dinhtungdu commented
@felipeelia I added since tags and fix the i18n issue.

2021-06-11 19:59 UTC, Rahmon approved these changes

2021-06-16 17:06 UTC, felipeelia requested changes

2021-06-16 17:06 UTC, felipeelia commented on includes/dashboard.php
> +				'sanitize_callback' => __NAMESPACE__ . '\sanitize_enable_dynamic_index',
Any reason why we are not calling absint here directly?

2021-06-16 17:06 UTC, felipeelia commented on includes/partials/settings-page.php
> +						<legend class="description"><?php esc_html_e( 'Enabling this setting let ElasticPress adjust the bulk index setting automatically for a more reliable and optimized index process.', 'elasticpres
Looking at how it looks like on the Settings page, shouldn't this be a label instead of a legend? Also, if that is the case, let's add the proper "for" to it, for accessibility and ease of use.

2021-06-16 17:06 UTC, felipeelia commented on includes/utils.php
> + */
As we are returning things here, can we add the proper `@return` tag to the doc?

2021-06-16 17:06 UTC, felipeelia commented on includes/utils.php
> +	} else {
We don't really need this else here, right?

2021-06-16 17:06 UTC, felipeelia commented on includes/utils.php
> +function get_ep_option( $key ) {
Can we add a `$default` parameter here to properly mimic WP functions?

2021-06-16 17:06 UTC, felipeelia commented on includes/utils.php
> + * @since 3.6
Same about SemVer, let's go with `3.6.0`.

2021-06-16 17:06 UTC, felipeelia commented on includes/utils.php
> + * @since 3.6
Same

2021-06-16 17:06 UTC, felipeelia commented on includes/utils.php
> + * @param mixed  $value Option value to be set.
The `@return` tag is needed here as well.

2021-06-16 17:06 UTC, felipeelia commented on includes/utils.php
> +function update_ep_option( $key, $value ) {
For this one we'll need to add `$autoload` (used in the update_option function.

2021-06-16 17:06 UTC, felipeelia commented on includes/utils.php
> +	} else {
This else can go away too.

2021-06-16 17:06 UTC, felipeelia commented on includes/utils.php
> +
As we are on it, can we add a delete_ep_option() function as well?

2021-06-17 04:02 UTC, dinhtungdu commented on includes/classes/Elasticsearch.php
> +	private function try_tuning_bulk_setting( $exec_time ) {
Ah, this is my mistake, changed to `protected`.

2021-06-17 04:16 UTC, dinhtungdu commented on includes/dashboard.php
> +				'sanitize_callback' => __NAMESPACE__ . '\sanitize_enable_dynamic_index',
Oh, we should do that actually! Thanks for pointing this out!

2021-06-17 04:24 UTC, dinhtungdu commented on includes/utils.php
> +
I think we should only add it when we need it. We can add it later when we refactor existing `get_site_option` and `get_option` calls to EP utils.

2021-06-17 08:42 UTC, dinhtungdu commented on includes/classes/Indexable.php
> +			}
Good catch!!! I fix this issue in https://github.com/10up/ElasticPress/commit/2f6a8dbf3d0f4f46123304680c1778a1c67db54b

2021-06-17 08:43 UTC, dinhtungdu commented
@felipeelia Thank you so much for the super detailed review! I addressed all problems you pointed out! Please give this one another look!

2022-01-04 18:26 UTC, closed without merging