Updated prepare_date_terms to only call date_i18n once
10up/ElasticPress pull request #1958
Opened 2020-11-05 20:39 UTC by brandon-m-skinner

### Description of the Change

Calling `date_i18n` a lot gets pretty expensive. Only calling it once for each `prepare_date_terms` call is much more efficient and make indexing faster.

Props @WPprodigy
cc: @rinatkhaziev @nickdaugherty @pschoffer @netsuso @parkcityj

### Alternate Designs

N/A

### Benefits

Removes extraneous calls to `date_i18n` and makes indexing faster.

### Possible Drawbacks

N/A

### Verification Process

There are 4 calls to `prepare_date_terms()` per post being indexed. Each call resulted in 12 calls to `date_i18n()`, which ends up going down a bit of a rabbit hole and eventually adding up to a lot of time spent doing filters and alloption calls. So per page of 500 posts being indexed, that is 24,000 calls (500 x 12*4)- seen in cachegrind.

Before the changes, a test group of 500 posts took 7.91601 seconds running prepare_date(). After this PR, 0.85888 seconds.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues

### Changelog Entry

Changed prepare_date_terms to only call date_i18n once. Props @WPprodigy

2020-12-22 17:36 UTC, tlovett1 requested changes

2020-12-22 17:36 UTC, tlovett1 commented on includes/classes/Indexable/Post/Post.php
> +			$index_in_combined_format = array_search( $term_name, array_keys( $terms_to_prepare ) );
This logic seems a bit strange. Can't you just use `$terms_to_prepare[ $term_name ]`? Also for `array_search` you should use the strict comparison parameter.

2021-01-04 21:22 UTC, WPprodigy commented on includes/classes/Indexable/Post/Post.php
> +			$index_in_combined_format = array_search( $term_name, array_keys( $terms_to_prepare ) );
It is a bit strange, but the tricky portion requiring this is that we need the index to access from `$combined_dates` on the next line. Given a data to prepare like "'2019-12-17 22:28:46'", `$combined_dates` looks like this:

```
Array
(
    [0] => 2019
    [1] => 12
    [2] => 51
    [3] => 350
    [4] => 17
    [5] => 2
    [6] => 2
    [7] => 22
    [8] => 28
    [9] => 46
    [10] => 201912
)
```

2021-05-24 19:02 UTC, Rahmon commented
Closing in favor of #2214

2021-05-24 19:02 UTC, closed without merging