Added action_set_object_terms
10up/ElasticPress pull request #1969
Opened 2020-11-05 21:47 UTC by brandon-m-skinner

Queues posts for re-indexing when their terms are changed

### Description of the Change

### Alternate Designs

### Benefits

### Possible Drawbacks

### Verification Process

### Checklist:

- [ ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues

### Changelog Entry

2021-12-15 18:35 UTC, rebeccahum requested changes
Left some notes. 

But overall, I think this is will prove to be useful, especially if we have clients with larger term sets — this way, they won't have to run a re-index to get the accurate terms assigned to posts.

2021-12-15 18:35 UTC, rebeccahum commented on includes/classes/Indexable/Post/SyncManager.php
> +		$post_id = $object_id;
Missing a check for `$this->kill_sync()`:

```suggestion
		if ( $this->kill_sync() ) {
			return;
		}
		$post_id = $object_id;
```

2021-12-15 18:35 UTC, rebeccahum commented on includes/classes/Indexable/Post/SyncManager.php
> +		$indexable = Indexables::factory()->get( 'post' );
For code consistency, let's use `$this->indexable_slug` even though it will end up evaluating to `post`:

```suggestion
		$indexable = Indexables::factory()->get( $this->indexable_slug );
```

2021-12-15 18:35 UTC, rebeccahum commented on includes/classes/Indexable/Post/SyncManager.php
> +
We should add a filter for skipping a sync triggered by term changes

2022-01-27 14:07 UTC, felipeelia commented
This also closes #750

2022-02-21 17:17 UTC, felipeelia commented
Closing in favor of https://github.com/10up/ElasticPress/pull/2603

2022-02-21 17:17 UTC, closed without merging