Add a way to change the ordering of the features on the Features page
10up/ElasticPress pull request #1987
Opened 2020-11-26 19:50 UTC by Rahmon

### Description of the Change

This PR adds two properties to the abstract class Feature that allow the developer to change the order of the features and chose if a feature should be on the left or right side when the features are listed on the Features page. Furthermore, changes are done in the `dashboard-page.php` to sort the array of features and to put on the left or right side.

### Alternate Designs

### Benefits

Change the order of the features to prioritize the most important, most used, or to show the features in a different way. 

### Possible Drawbacks

### Verification Process

This has been tested manually just to validate the implementation. 

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues

Closes #1983 

### Changelog Entry

Added custom sorting to features on the Feature page.

2021-05-26 14:24 UTC, felipeelia requested changes

2021-05-26 14:24 UTC, felipeelia commented on includes/classes/Feature.php
> +	 * @since  3.5.1
@Rahmon can we update these 2 @since tags before we merge it?

2021-05-26 14:24 UTC, felipeelia commented on includes/partials/dashboard-page.php
> +				if ( $feature_a->order == $feature_b->order ) {
PHPCS gives a warning about this line. Any chance we cast both values to integer at the beginning of the function?

2021-05-26 19:20 UTC, Rahmon commented on includes/classes/Feature.php
> +	 * @since  3.5.1
Done.

2021-05-26 19:29 UTC, Rahmon commented on includes/partials/dashboard-page.php
> +				if ( $feature_a->order == $feature_b->order ) {
Refactored. Thanks for it.

2021-05-27 17:57 UTC, felipeelia approved these changes

2021-05-28 13:42 UTC, merged