Add test to site health
10up/ElasticPress pull request #2084
Opened 2021-02-15 20:35 UTC by Rahmon

### Description of the Change

This change adds a way to add tests to Site Health Check and as well a test to check Elasticsearch connection.

### Alternate Designs

### Benefits

It's possible to check the status of the Elasticsearch connection on the Site Health page and new tests can be added.

### Possible Drawbacks

### Verification Process

This change can be tested by accessing the Site Health page under Tools menu.

![image](https://user-images.githubusercontent.com/6010232/107990633-9be16080-6fb3-11eb-829a-d32dc9d05c39.png)

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues

Closes: #1316 

### Changelog Entry

Added Elasticsearch connection check to Site Health page.

2021-03-05 14:42 UTC, felipeelia requested changes

2021-03-05 14:42 UTC, felipeelia commented on includes/classes/HealthCheck/HealthCheckElasticsearch.php
> +				esc_url( admin_url( 'admin.php?page=elasticpress-settings' ) ),
When the plugin is network activated, this link seems to point to the wrong URL. Can you please check, @Rahmon ?

2021-03-08 12:09 UTC, Rahmon commented on includes/classes/HealthCheck/HealthCheckElasticsearch.php
> +				esc_url( admin_url( 'admin.php?page=elasticpress-settings' ) ),
You're right. Fixed and thanks :smile:

2021-04-09 14:29 UTC, felipeelia approved these changes

2021-04-30 17:20 UTC, merged