WIP: Feature/category not in support
10up/ElasticPress pull request #2174
Opened 2021-04-17 22:33 UTC by oscarssanchez

### Description of the Change

### Alternate Designs

### Benefits

### Possible Drawbacks

### Verification Process

### Checklist:

- [ ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues

### Changelog Entry

2021-04-23 14:23 UTC, felipeelia requested changes

2021-04-23 14:23 UTC, felipeelia commented on includes/classes/Indexable/Post/Post.php
> +			);
@oscarssanchez the code looks good! Can we just move this `$use_filters` to below the `$filter` declaration, to keep consistency with the other occurrences of this structure in the code? This is what I mean:

```
		if ( ! empty( $args['category__not_in'] ) ) {
			$filter['bool']['must'][]['bool']['must_not'] = array(
				'terms' => array(
					'terms.category.term_id' => (array) $args['category__not_in'],
				),
			);

			$use_filters = true;
		}
```

Also, as we are aiming this for 3.6.0, can you edit the `@since` tag? And as you are on it, what do you think about adding `tag__not_in` as well?

Thanks!

2021-05-04 23:29 UTC, oscarssanchez commented
Added `tag__not_in` support @felipeelia can you please take another peek?

2021-05-06 14:20 UTC, felipeelia commented
@oscarssanchez I'm terribly sorry for not seeing this before but can we wrap those `(array) $variable` statements with an `array_values()` call? That way we avoid problems if some plugin or theme decides to send an associative array. Again, sorry for the back and forth here.

2021-05-18 16:13 UTC, Rahmon approved these changes
LGTM :+1:

2021-05-19 17:33 UTC, Rahmon commented
@oscarssanchez can you please update the PR to be able to merge?

2021-05-20 21:00 UTC, oscarssanchez commented
Branch updated @Rahmon :)

2021-05-27 17:29 UTC, merged