Add post__name_in support
10up/ElasticPress pull request #2194
Opened 2021-05-04 18:05 UTC by oscarssanchez

### Description of the Change

Hi @felipeelia , can you please review this PR implementing https://github.com/10up/ElasticPress/issues/1519#issuecomment-541488811 ?

### Alternate Designs

### Benefits

Adds support for `post__name_in` 

### Possible Drawbacks

### Verification Process

* Unit tests
* Tested it worked with a normal `WP_Query` object and using the `pre_get_posts` hook

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues

### Changelog Entry

2021-05-06 13:19 UTC, felipeelia requested changes

2021-05-06 13:19 UTC, felipeelia commented on includes/classes/Indexable/Post/Post.php
> +					'post_name.raw' => $args['post_name__in'],
@oscarssanchez I'm afraid that if `post_name__in` is an associative array, it will become an object (rather than an array) in JSON, and ES will fail. Can you please change
`'post_name.raw' => $args['post_name__in'],`
to
`'post_name.raw' => array_values( (array) $args['post_name__in'] ),`
Thanks!

2021-05-13 00:45 UTC, oscarssanchez commented on includes/classes/Indexable/Post/Post.php
> +					'post_name.raw' => $args['post_name__in'],
Makes sense @felipeelia !

2021-05-18 15:50 UTC, Rahmon requested changes

2021-05-18 15:50 UTC, Rahmon commented on tests/php/indexables/TestPost.php
> +			'post_name__in' => 'findme-name-in',
@oscarssanchez I would add a test passing an array in `post_name__in` since this parameter [expects an array](https://developer.wordpress.org/reference/classes/wp_query/#post-page-parameters). Just to make sure it's working in this case.

2021-05-20 21:22 UTC, oscarssanchez commented on tests/php/indexables/TestPost.php
> +			'post_name__in' => 'findme-name-in',
Thanks @Rahmon I have added tests for this.

2021-05-21 14:22 UTC, Rahmon approved these changes
LGTM :+1:

2021-05-21 14:39 UTC, felipeelia approved these changes

2021-05-21 14:45 UTC, merged