Updated prepare_date_terms to only call date_i18n once
10up/ElasticPress pull request #2214
Opened 2021-05-24 18:44 UTC by Rahmon

This is a "take over" of #1958  just to address some minor things.

### Description of the Change

Calling `date_i18n` a lot gets pretty expensive. Only calling it once for each `prepare_date_terms` call is much more efficient and make indexing faster.

Props @WPprodigy
cc: @rinatkhaziev @nickdaugherty @pschoffer @netsuso @parkcityj

### Alternate Designs

N/A

### Benefits

Removes extraneous calls to `date_i18n` and makes indexing faster.

### Possible Drawbacks

N/A

### Verification Process

There are 4 calls to `prepare_date_terms()` per post being indexed. Each call resulted in 12 calls to `date_i18n()`, which ends up going down a bit of a rabbit hole and eventually adding up to a lot of time spent doing filters and alloption calls. So per page of 500 posts being indexed, that is 24,000 calls (500 x 12*4)- seen in cachegrind.

Before the changes, a test group of 500 posts took 7.91601 seconds running prepare_date(). After this PR, 0.85888 seconds.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues

Closes: #1958 

### Changelog Entry

Changed prepare_date_terms to only call date_i18n once. Props @WPprodigy

2021-05-26 14:08 UTC, felipeelia requested changes

2021-05-26 14:08 UTC, felipeelia commented on includes/classes/Indexable/Post/Post.php
> +	private function prepare_date_terms( $date_to_prepare ) {
@Rahmon there is no reason to keep this method private. Let's make it public, as it doesn't change any instance attribute...

2021-05-26 14:08 UTC, felipeelia commented on includes/classes/Indexable/Post/Post.php
> +		$combined_dates = explode( '||', date_i18n( $date_format, strtotime( $date_to_prepare ) ) );
heh, this was clever!

2021-05-26 14:08 UTC, felipeelia commented on tests/php/indexables/TestPost.php
> +	protected function get_private_function( $functionName, $className = '\ElasticPress\Indexable\Post\Post' ) {
making `prepare_date_terms` public will be good to get rid of this as well. It is a nice piece of code, though.

2021-05-26 14:42 UTC, felipeelia commented
@Rahmon I forgot to mention but there are some warnings in PHPCS that should be addressed as well. Thanks!

2021-05-26 16:43 UTC, WPprodigy commented on includes/classes/Indexable/Post/Post.php
> +	private function prepare_date_terms( $date_to_prepare ) {
I will note that private is safer long-term, since it ensures you can make changes to it in the future and only have to account for the usage in the class itself, and not track down if anything else is relying / extending on it. Once public, you have to permanently keep backwards compatibility.

2021-05-26 17:03 UTC, Rahmon commented on tests/php/indexables/TestPost.php
> +		$this->assertArrayHasKey( 'dayofyear', $return_prepare_date_terms );
Added

2021-05-26 17:04 UTC, felipeelia commented on includes/classes/Indexable/Post/Post.php
> +	private function prepare_date_terms( $date_to_prepare ) {
Thanks for weighing in @WPprodigy. Although I partially agree with you:
1. This entire class is probably one of the most extended in custom solutions that involve new Indexables, so just because of that, we would have enough reasons to make it at least protected.
2. From an OOP perspective, this is just a "utility" function, receiving one input and returning an output without modifying the instance itself, making things _easier_ to track down.
3. If we decide to make any change in the way the plugin creates those date_terms, people would be relying on the indexed values anyway.

2021-05-27 13:22 UTC, felipeelia approved these changes

2021-05-27 15:04 UTC, merged