Fix WP_Query_User when it tries to sort the results
10up/ElasticPress pull request #2226
Opened 2021-06-01 21:09 UTC by Rahmon

### Description of the Change

This changes updates to use keyword fields to sort in the WP_User_Query and adds tests to ensure we are using these fields.

### Alternate Designs

### Benefits

Elasticsearch will not fail and fall back to MySQL.

### Possible Drawbacks

### Verification Process

1. Enable Users feature
2. Go to a page/post and add a paragraph block
3. Type `@` and try to search a user e.g. `@admin`
4. Check if the results were provided by Elasticsearch.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests passed.

### Applicable Issues

Closes: #2225 

### Changelog Entry

Fixed sort for WP_User_Query

2021-06-10 12:46 UTC, felipeelia requested changes

2021-06-10 12:46 UTC, felipeelia commented on tests/php/indexables/TestUser.php
> +		$this->assertEquals( 'Zoey', $users_display_name_fetched[0] );
@Rahmon it seems to be counterintuitive to rely on a case-sensitive sorting while WP's is case insensitive. Also, for fields in the posts indexable we have [a "sortable" field](https://github.com/10up/ElasticPress/blob/develop/includes/mappings/post/7-0.php#L265) that we could replicate here. Do you mind taking care of that?

2021-06-11 17:22 UTC, Rahmon commented on tests/php/indexables/TestUser.php
> +		$this->assertEquals( 'Zoey', $users_display_name_fetched[0] );
Sure. Thanks for that @felipeelia

2021-06-16 14:15 UTC, felipeelia submitted a review, later dismissed

2021-06-16 16:11 UTC, felipeelia commented
@Rahmon did you test it with Elasticsearch 5.6.16 (the version shipped with WP Local Docker)? I'm using the following snippet in theme's header.php:

```
new WP_User_Query(
	[
		'search'  => 'test',
		'orderby' => 'display_name',
	]
);
```

As is, I receive a 400 error saying:
> Fielddata is disabled on text fields by default. Set fielddata=true on [display_name.sortable] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.

If I change `wp-content/plugins/elasticpress/includes/mappings/user/initial.php` to look like this, it works:

```
'display_name'    => array(
	'type'   => 'text',
	'fields' => array(
		'raw'      => array(
			'type'                => 'keyword',
			'ignore_above' => 10922,
		),
		'sortable' => array(
			'type'         => 'keyword',
			'ignore_above' => 10922,
			'normalizer'   => 'lowerasciinormalizer',
		),
	),
),
```

Can you please check it? Thanks

2021-06-21 16:39 UTC, Rahmon commented
> @Rahmon did you test it with Elasticsearch 5.6.16 (the version shipped with WP Local Docker)? I'm using the following snippet in theme's header.php:
> 
> ```
> new WP_User_Query(
> 	[
> 		'search'  => 'test',
> 		'orderby' => 'display_name',
> 	]
> );
> ```
> 
> As is, I receive a 400 error saying:
> 
> > Fielddata is disabled on text fields by default. Set fielddata=true on [display_name.sortable] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.
> 
> If I change `wp-content/plugins/elasticpress/includes/mappings/user/initial.php` to look like this, it works:
> 
> ```
> 'display_name'    => array(
> 	'type'   => 'text',
> 	'fields' => array(
> 		'raw'      => array(
> 			'type'                => 'keyword',
> 			'ignore_above' => 10922,
> 		),
> 		'sortable' => array(
> 			'type'         => 'keyword',
> 			'ignore_above' => 10922,
> 			'normalizer'   => 'lowerasciinormalizer',
> 		),
> 	),
> ),
> ```
> 
> Can you please check it? Thanks

@felipeelia I've updated the mapping and updated some tests to check if the query uses the Elasticsearch to retrieve the users.

2021-06-24 17:17 UTC, felipeelia approved these changes

2021-06-24 17:19 UTC, merged