Widget to search only on comments
10up/ElasticPress pull request #2238
Opened 2021-06-24 12:55 UTC by Rahmon

### Description of the Change

This change adds a widget to search for comments since PR #1531 adds a Comments Indexable.

### Alternate Designs

### Benefits

### Possible Drawbacks

### Verification Process

1. Enable Comments Feature
2. Add the widget ElasticPress - Comments
3. Search for a comment

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests passed.

### Applicable Issues

Closes #2177 

### Changelog Entry

Added ElasticPress - Comments widget

2021-06-28 17:25 UTC, felipeelia requested changes

2021-06-28 17:25 UTC, felipeelia commented on assets/css/comments.css
> +	border: 2px dotted #171923;
@Rahmon you made me curious about this line here. Any reason why did you pick this color? :)

2021-06-28 17:25 UTC, felipeelia commented on assets/js/comments.js
> +			`;
@Rahmon as we've talked, let's give the devs a chance to change this output here.

2021-06-28 17:25 UTC, felipeelia commented on assets/js/comments.js
> +	resultList.innerHTML = items;
@Rahmon also a good place for a chance to change it.

2021-06-28 17:25 UTC, felipeelia commented on assets/js/comments.js
> +	resultList.innerHTML = `<li class="ep-widget-search-comments-result-item">${window.epc.noResultsFoundText}</li>`;
@Rahmon In addition to a chance to change it, perhaps we should give it another class as well. Thoughts?

2021-06-28 17:25 UTC, felipeelia commented on includes/classes/Feature/Comments/Comments.php
> +	 * @since  3.6
Do you mind changing all the 3.6 to 3.6.0?

2021-06-28 17:25 UTC, felipeelia commented on includes/classes/Feature/Comments/Comments.php
> +	 * Registers the API endpoint to search for comments
It would be great to have a `@since` here as well, just to keep consistency.

2021-06-28 17:25 UTC, felipeelia commented on includes/classes/Feature/Comments/Comments.php
> +	 * @return array
It would be great to have a `@since` here as well, just to keep consistency.

2021-06-28 17:25 UTC, felipeelia commented on includes/classes/Feature/Comments/Comments.php
> +		$comment_query = new \WP_Comment_Query( $args );
This seems to be a good place for a filter. Also, shouldn't `$args` use the get_indexable_comment_types() as well?

2021-06-28 17:25 UTC, felipeelia commented on includes/classes/Feature/Comments/Comments.php
> +		return $return;
another good place for a filter. I wonder if we shouldn't have pre and post_search_widget actions as well.

2021-06-28 17:25 UTC, felipeelia commented on includes/classes/Feature/Comments/Widget.php
> + * @since  3.6
3.6.0 :grimacing:

2021-06-28 17:25 UTC, felipeelia commented on includes/classes/Feature/Comments/Widget.php
> +	 * @since 3.6
3.6.0 :grimacing:

2021-06-28 17:25 UTC, felipeelia commented on includes/classes/Feature/Comments/Widget.php
> +	 * @since  3.6
3.6.0 :grimacing:

2021-06-28 17:25 UTC, felipeelia commented on includes/classes/Feature/Comments/Widget.php
> +		$comments_search_form = ob_get_clean();
Why run this through a buffer if you are not planning to give the devs the chance to modify it?

2021-06-28 17:25 UTC, felipeelia commented on includes/classes/Feature/Comments/Widget.php
> +		$script_data['restApiEndpoint'] = get_rest_url( null, 'elasticpress/v1/comments' );
Shouldn't we set the entire `$script_data` array before running it through the filter? This way people can use a custom endpoint if they prefer.

2021-06-28 17:25 UTC, felipeelia commented on includes/classes/Feature/Comments/Widget.php
> +		echo wp_kses_post( $comments_search_form );
A good point for a filter? Check how it is done in Facets.

2021-06-28 17:25 UTC, felipeelia commented on includes/classes/Feature/Comments/Widget.php
> +		</p>
IIRC @brandwaffle mentioned the necessity of a list where the user could select post types. Do you remember that?

2021-06-28 17:25 UTC, felipeelia commented on includes/classes/Feature/Comments/Widget.php
> +	 * @since  2.2
Probably 3.6.0?

2021-06-28 17:30 UTC, Rahmon commented on assets/js/comments.js
> +			`;
@felipeelia Added :pray:

2021-06-28 17:34 UTC, Rahmon commented on assets/css/comments.css
> +	border: 2px dotted #171923;
@felipeelia I've chosen this color to not use pure black but we can change it.

2021-06-28 18:06 UTC, Rahmon commented on includes/classes/Feature/Comments/Widget.php
> +		</p>
@felipeelia the user can change the post types using a filter. IIRC this (select the post types) would be included in the next version.

2021-06-28 18:06 UTC, Rahmon commented on includes/classes/Feature/Comments/Widget.php
> +	 * @since  2.2
Updated.

2021-06-28 18:57 UTC, Rahmon commented on assets/js/comments.js
> +	resultList.innerHTML = `<li class="ep-widget-search-comments-result-item">${window.epc.noResultsFoundText}</li>`;
I've updated to `ep-widget-search-comments-result-item-not-found`. Makes sense?

2021-06-28 18:57 UTC, Rahmon commented on includes/classes/Feature/Comments/Comments.php
> +	 * @since  3.6
Done

2021-06-28 18:58 UTC, Rahmon commented on includes/classes/Feature/Comments/Widget.php
> +		$script_data['restApiEndpoint'] = get_rest_url( null, 'elasticpress/v1/comments' );
I've moved the `restApiEndPoint` to before running the filter

2021-06-28 19:00 UTC, Rahmon commented on includes/classes/Feature/Comments/Widget.php
> +		echo wp_kses_post( $comments_search_form );
Thanks for pointing it. I've added.

2021-06-29 12:21 UTC, felipeelia requested changes

2021-06-29 12:21 UTC, felipeelia commented on includes/classes/Feature/Comments/Comments.php
> +		$args = apply_filters( 'ep_widget_search_comments_args', $default_args );
@Rahmon as we've discussed, let's go with `ep_comment_search_widget_args` to follow the `ElasticPress > Comments > Search Widget`.

2021-06-29 12:21 UTC, felipeelia commented on includes/classes/Feature/Comments/Widget.php
> +		$script_data = apply_filters( 'ep_widget_search_comments_l10n_data_script', $default_script_data );
Let's go with `ep_comment_search_widget_l10n_data_script`  here? Using `comment` in the singular here to follow what we've established in the indexable.

2021-06-29 13:55 UTC, Rahmon commented on includes/classes/Feature/Comments/Comments.php
> +		$args = apply_filters( 'ep_widget_search_comments_args', $default_args );
updated

2021-06-29 22:02 UTC, felipeelia commented on includes/classes/Feature/Comments/Comments.php
> +		$body   = json_decode( $request->get_body(), true );
@Rahmon any reason why using POST and the request body instead of another GET parameter? This would be more consistent with regular search and even with the other REST API endpoints, IMO.

2021-06-29 22:04 UTC, felipeelia commented on includes/classes/Feature/Comments/Comments.php
> +		}
what do you think about moving this to before the post_type stuff in order to fail earlier if possible?

2021-06-29 22:07 UTC, felipeelia commented on includes/classes/Feature/Comments/Comments.php
> +			'post_type'   => $post_type,
It seems like, as is, `$post_type` would be set only if a postType was passed to the request. Can you double-check that, please?

2021-06-30 12:18 UTC, Rahmon commented on includes/classes/Feature/Comments/Comments.php
> +		$body   = json_decode( $request->get_body(), true );
I updated to use GET

2021-06-30 12:18 UTC, Rahmon commented on includes/classes/Feature/Comments/Comments.php
> +		}
Makes sense. I updated it.

2021-06-30 12:19 UTC, Rahmon commented on includes/classes/Feature/Comments/Comments.php
> +			'post_type'   => $post_type,
I updated to use the search post types if the post_type filter is empty

2021-06-30 17:39 UTC, felipeelia approved these changes

2021-06-30 17:45 UTC, merged