Add aria-labels and title attributes to icon hyperlinks in the header toolbar
10up/ElasticPress pull request #2304
Opened 2021-08-12 14:10 UTC by claytoncollie

### Description of the Change

Issue #2286 

### Alternate Designs

This was the least intrusive option. The second option would be tooltips on each icon which would require additional javascript. The third option would be to add a text label just below the icon which probably involves some sort of design change and sign-off.

### Benefits

1. Screen readers will be able to identify the links
2. New users will understand the icon's function before selecting it

### Verification Process

To verify, I went to the wp-admin dashboard for the plugin and hovered over each icon to see the title attribute.

Also ran `composer run lint-fix` in my editor to make sure my code formatting was correct.

### Checklist:

- [X ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Changelog Entry

Add title attributes and aria-labels to each icon hyperlink in the header toolbar

2021-08-12 14:20 UTC, felipeelia requested changes

2021-08-12 14:20 UTC, felipeelia commented on includes/partials/header.php
> +			<a class="dashicons cancel-sync dashicons-no" title="<?php esc_html_e( 'Cancel Sync', 'elasticpress' ); ?>" aria-label="<?php esc_html_e( 'Cancel Sync', 'elasticpress' ); ?>"></a>
Hi @claytoncollie, thank you very much for the Pull Request! Do you mind changing the esc_html_e() calls to esc_attr_e(), as those strings are inside attributes? Thanks!

2021-08-13 13:48 UTC, claytoncollie commented on includes/partials/header.php
> +			<a class="dashicons cancel-sync dashicons-no" title="<?php esc_html_e( 'Cancel Sync', 'elasticpress' ); ?>" aria-label="<?php esc_html_e( 'Cancel Sync', 'elasticpress' ); ?>"></a>
All done @felipeelia

2021-08-13 13:50 UTC, felipeelia approved these changes

2021-08-13 13:50 UTC, felipeelia commented on includes/partials/header.php
> +			<a class="dashicons cancel-sync dashicons-no" title="<?php esc_html_e( 'Cancel Sync', 'elasticpress' ); ?>" aria-label="<?php esc_html_e( 'Cancel Sync', 'elasticpress' ); ?>"></a>
Excellent @claytoncollie, thanks!

2021-08-16 13:53 UTC, merged