Fix/post tag duplication
10up/ElasticPress pull request #2341
Opened 2021-09-07 05:13 UTC by oscarssanchez

### Description of the Change

This PR aims to fix three things. First, there's a duplication of `terms.post_tag.slug` similar to the problem that was happening in https://github.com/10up/ElasticPress/issues/2242 when you are making with similar args: 

```
$args = [
	'ep_integrate' => true,
	'tag' => array( 'slug1, slug2' ),
];
```

This is fixed here: https://github.com/10up/ElasticPress/compare/fix/post-tag-duplication?expand=1#diff-7004c1b9f26ece8d68d4d3b7b822331a1f1e0cdf34a5eda1aa146d930d21ad08R1007 adding `post_tag` and `category` as these are WP Core default taxonomies, and I have added the filter 'ep_post_tax_excluded_wp_query_root_check' in case this is needed to be extended by a developer.

Second, doing a query for more than one term in an array form does not work, as it will format the `tag` arg like a comma separated string.

Third, searching for multiple tags with comma separated tags does not work at all. This is allowed by core: https://developer.wordpress.org/reference/classes/wp_query/#tag-parameters

It looks like core will translate both the array and comma separated strings as comma separated, which is different than how it formats a tax query, therefore that part remains unaffected  

### Alternate Designs

### Benefits

Expand `WP_Query`

### Possible Drawbacks

### Verification Process

### Checklist:

- [ ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues

### Changelog Entry

2021-09-14 16:40 UTC, Rahmon commented on includes/classes/Indexable/Post/Post.php
> +			if ( ! is_array( $args['tag'] ) && strpos( $args['tag'], ',' ) ) {
I'm a little concerned about `strpos` because it could return 0 and evaluate to `false`. Other than that, wouldn't be an issue with just one tag?

2021-09-14 16:40 UTC, Rahmon commented on tests/php/indexables/TestPost.php
> +		$query2 = new \WP_Query( $query2_args );
After these WP_Query, can you check if the data was retrieved using elasticsearch?

```php
foreach ( $query1->results as $item ) {
	$this->assertTrue( $item->elasticsearch );
}
```

2021-09-21 15:07 UTC, oscarssanchez commented on tests/php/indexables/TestPost.php
> +		$query2 = new \WP_Query( $query2_args );
Thanks @Rahmon I have addressed this here: https://github.com/10up/ElasticPress/pull/2341/commits/bbf5f9b114ad9fd10ea66f0df57576fc2740bd80

2021-09-21 15:09 UTC, oscarssanchez commented on includes/classes/Indexable/Post/Post.php
> +			if ( ! is_array( $args['tag'] ) && strpos( $args['tag'], ',' ) ) {
Good call @Rahmon , I have addressed it here https://github.com/10up/ElasticPress/pull/2341/commits/1d71d8a622aef3eec3c580ace6ae69cbe46785e0

For your other question, if it is a single tag the evaluation of this logic will be false. I have checked it works with one tag as well.

2021-09-21 20:51 UTC, Rahmon submitted a review, later dismissed

2021-09-22 14:03 UTC, felipeelia requested changes

2021-09-22 14:03 UTC, felipeelia commented on includes/classes/Indexable/Post/Post.php
> +			);
@oscarssanchez @Rahmon I'm pretty sure this should be like the following, right?
```
			$excluded_tax_from_root_check = apply_filters(
				'ep_post_tax_excluded_wp_query_root_check',
				[
					'category',
					'post_tag',
				]
			);
```
Also, we need docs for this.

2021-09-22 14:07 UTC, felipeelia commented on includes/classes/Indexable/Post/Post.php
> +			);
Actually, looking at the code, that variable should be set outside of the foreach, there seems to be no point in setting that variable with the same value on every iteration.

2021-09-23 15:03 UTC, felipeelia requested changes

2021-09-23 15:03 UTC, felipeelia commented on includes/classes/Indexable/Post/Post.php
> +			'ep_post_tax_excluded_wp_query_root_check',
@oscarssanchez not sure if this is under your radar already but we still need docs for this.

2021-09-24 16:21 UTC, felipeelia approved these changes

2021-09-24 17:30 UTC, merged