Add helper get_total_objects_for_query_from_db() which counts directly from the DB
10up/ElasticPress pull request #2571
Opened 2022-01-26 20:29 UTC by rebeccahum

### Description of the Change

We're noticing that on very large sites, the query to count the total objects in `get_total_objects_for_query()` dies. This PR adds an abstracted helper method `get_total_objects_for_query_from_db()` that breaks it down using `wp_count_posts` to count the posts directly from the DB.

### Alternate Designs

N/A.

### Possible Drawbacks

A bit more processing during indexing if the count query has died, but at least the user will have an idea of the number of posts, rather than "0".

### Verification Process

On a verrrry large site where it says `0` as the total objects, i.e. `Processed x/0`, apply the PR and expect it to return a number.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Changelog Entry

### Credits

Props @

2022-01-27 11:08 UTC, felipeelia requested changes

2022-01-27 11:08 UTC, felipeelia commented on includes/classes/Indexable/Post/Post.php
> +				if ( ! in_array( $post_status, $query_args['post_status'] ) ) {
Do you mind changing this to 
`in_array( $post_status, $query_args['post_status'], true )` @rebeccahum? As is it triggers a warning in PHPCS and as we are checking strings, I don't think it will be a problem.

2022-01-27 11:08 UTC, felipeelia commented on includes/classes/Indexable/Post/Post.php
> +	 * @param array $query_args The query args.
Can you please add a `@since 4.0.0` in the doc block? Thanks!

2022-01-27 11:08 UTC, felipeelia commented on includes/classes/Indexable/Post/Post.php
> +	public function get_total_objects_for_query_from_db( $query_args ) {
As it is only called by a private method (`get_total_objects_for_query()`), I guess we can change the method visibility to be also private.
I'd prefer to have them both as `protected` so people can extend the class without having to copy/paste code, though. Right now, anyone extending this class and using the `query_db` method will have to make a copy of `get_total_objects_for_query()` to have it working.
Thoughts?

2022-01-27 17:06 UTC, rebeccahum commented
@felipeelia Thanks for your feedback! All have been addressed now.

2022-01-28 17:34 UTC, felipeelia approved these changes

2022-01-28 19:09 UTC, merged