Add support for multiple aggregations
10up/ElasticPress pull request #2682
Opened 2022-03-27 21:59 UTC by felipeelia

### Description of the Change

Currently, the plugin only supports a single array as the `aggs` parameter of WP_Query. This PR changes that to also support an array of aggregations. This will be needed to implement #1440 in a cleaner way.

Closes #636

### Changelog Entry

Added: Support for an array of aggregations in the `aggs` parameter of WP_Query.

### Credits

Props @felipeelia

2022-03-28 19:39 UTC, oscarssanchez requested changes

2022-03-28 19:39 UTC, oscarssanchez commented on includes/classes/Indexable/Post/Post.php
> +			if ( isset( $args['aggs'][0] ) ) {
Would it be better to check if this is an array with `is_array()` ? Right now I don't think it would do any harm, but i'm thinking if there's ever a case where we offer an aggregations filter for example, and people can manipulate the array indexes. If there's not `$args['aggs'][0] `but there's `$args['aggs'][1]` this code will not run.

2022-03-29 14:07 UTC, felipeelia commented on includes/classes/Indexable/Post/Post.php
> +			if ( isset( $args['aggs'][0] ) ) {
I've made the changes we discussed in slack @oscarssanchez . Do you mind giving yet another look at it? Thanks!

2022-03-29 17:04 UTC, oscarssanchez approved these changes

2022-03-29 17:04 UTC, merged