Change sync button title attribute
10up/ElasticPress pull request #2814
Opened 2022-06-01 07:50 UTC by burhandodhy

### Description of the Change
This PR changes the Sync button title attribute to `Sync` and also add the E2E test.

Closes #2793 

### Verification Process
- Go to Settings Page.
- Hover on the Sync button. The title would be `Sync`

### Changelog Entry

Changed: Sync button Title.
### Credits

Props @burhandodhy @JakePT

2022-06-07 14:10 UTC, felipeelia commented
@burhandodhy instead of simply "Sync", let's say "Sync Page" (and "Settings Page".)

2022-06-07 14:10 UTC, felipeelia commented
@burhandodhy instead of simply "Sync", let's say "Sync Page" (and "Settings Page".)

2022-06-13 20:32 UTC, felipeelia requested changes

2022-06-13 20:32 UTC, felipeelia commented on tests/cypress/integration/admin/settings-page.spec.js
> +});
It is GREAT to see tests like these coming through, @burhandodhy, congrats, and thanks! Can we please move it from a whole new test to the already existent `general.spec.js`? The links should be on all (or almost all) pages, so although it makes sense to pick one to check, we can save a `settings-page.spec.js` to something particular to that page, like checking if tabs change, etc. What do you think?

2022-06-14 05:41 UTC, burhandodhy commented on tests/cypress/integration/admin/settings-page.spec.js
> +});
@felipeelia agree with you. `settings-page.spec.js` should only have tests that are related to settings page. I move the test to general.spec.js

2022-06-14 14:04 UTC, merged