Support transforming legacy widgets to blocks and hide widgets when the blocks are available
10up/ElasticPress pull request #2819
Opened 2022-06-02 14:18 UTC by JakePT

### Description of the Change

This PR does two things:

1. Adds support for transforming the legacy Facet and Related Posts widgets into blocks. For these widgets when the block icon is clicked the _Transform to_ menu will include the new block versions of these widgets. The settings of the legacy widget will be carried over to the block.
2. Hides the Facet and Related Posts widgets from the Legacy Widget block. This means that when the block editor is being used there won't be two Facet or Related Posts blocks, which could cause confusion. This won't affect any existing instances of the legacy widgets, which will still be visible and editable, but it will prevent new instances being added. The legacy widgets will also still be usable if the site is using the Classic Widgets plugin, or similar, to disable the block editor for widgets.

Both changes are implemented as per the guidance in the [Block Editor Handbook](https://developer.wordpress.org/block-editor/how-to-guides/widgets/legacy-widget-block/#allowing-migration-to-a-block) and the behaviour is consistent with how most core legacy widgets are handled, such as Search.

Closes #2792

### Possible Drawbacks

While existing block instances won't be affected, the user will not be able to add new instances of the legacy widget. 

However, if the user doesn't want to switch existing instances to the block and needs to add new legacy widget instances, then there are two workarounds:

1. Use the core Widget Group block, which will wrap the block in the markup defined by the theme for the widget area.
2. Un-hide the legacy widgets by using the `widget_types_to_hide_from_legacy_widget_block` filter hook to remove their IDs from the list filtered by the hook.

### Verification Process

1. Before applying this PR, add several Facet and Related Posts legacy widget blocks with a variety of settings.
2. After applying the PR, go to the Widgets editor and the legacy widget blocks should still be visible.
3. Attempt to add a new block, when searching for "Facet" or "Related Posts" only one option from ElasticPress should appear for each and it should be the block, not the legacy widget.
4.  Install and activate [Classic Widgets](https://wordpress.org/plugins/classic-widgets/). With this activated the legacy widgets should be available in the widgets editor. 
5. Deactivate the plugin.
6. On the widgets screen, select each legacy widget and click the block's icon in the block toolbar. There should be an option to transform it into the block version of the widget. Clicking to transform the widget should convert it to the block and the settings of the widget should be reflected on the new block. If the widget had a Title this should be added as a heading block before the new block.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Changelog Entry

Added - Support for transforming instances of the legacy Facet and Related Posts widgets into blocks.
Changed - The legacy Facet and Related Posts widgets are now hidden when using the block editor.

### Credits

Props @JakePT

2022-07-25 09:49 UTC, JakePT commented
I've finally added complete tests for the Related Posts block, but the Facets block still needs new tests as the current tests are based on using the Legacy Widget as a block.

2022-08-10 19:52 UTC, felipeelia requested changes
Overall it looks really good @JakePT. Left some comments about specific items.

I'd like to know your thoughts about testing the "transform" part of those blocks. Isn't that worth testing in Cypress?

2022-08-10 19:52 UTC, felipeelia commented on tests/cypress/integration/features/facets.spec.js
> +	it('Facet block', () => {
@JakePT do you mind rephrasing this to describe what is being tested?

2022-08-10 19:52 UTC, felipeelia commented on tests/cypress/integration/features/facets.spec.js
> +	it('Facet widget', () => {
@JakePT same here

2022-08-10 19:52 UTC, felipeelia commented on tests/cypress/integration/features/facets.spec.js
> +		cy.wpCli('wp plugin deactivate classic-widgets');
@JakePT we have a command to activate and deactivate plugins. I'd prefer to stick with that just to be sure any performance improvement we have is applied across the entire test suite.

2022-08-10 19:52 UTC, felipeelia commented on tests/cypress/integration/features/facets.spec.js
> +		cy.wpCli('plugin install classic-widgets');
@JakePT can we install the plugin during the env setup? It would be a matter of adding it to the [.wp-env](https://github.com/10up/ElasticPress/blob/develop/.wp-env.json) file. Hopefully that gets cached in a good way (if not now, in the future) and it doesn't slow down the test execution.

2022-08-10 19:52 UTC, felipeelia commented on tests/cypress/support/commands.js
> +});
I wonder if we shouldn't start a new file only with blocks. Thoughts?

2022-08-11 11:52 UTC, JakePT commented on tests/cypress/integration/features/facets.spec.js
> +	it('Facet block', () => {
@felipeelia Done.

2022-08-11 11:53 UTC, JakePT commented on tests/cypress/integration/features/facets.spec.js
> +	it('Facet widget', () => {
@felipeelia Done.

2022-08-11 11:53 UTC, JakePT commented on tests/cypress/integration/features/facets.spec.js
> +		cy.wpCli('wp plugin deactivate classic-widgets');
@felipeelia Done.

2022-08-11 11:53 UTC, JakePT commented on tests/cypress/integration/features/facets.spec.js
> +		cy.wpCli('plugin install classic-widgets');
@felipeelia Done.

2022-08-11 11:53 UTC, JakePT commented on tests/cypress/support/commands.js
> +});
@felipeelia Done.

2022-08-12 18:41 UTC, felipeelia approved these changes

2022-08-12 18:55 UTC, merged