Restrict to convert meta value into date if year is greater than 2099
10up/ElasticPress pull request #2828
Opened 2022-06-06 05:53 UTC by burhandodhy

### Description of the Change
`prepare_date_meta_values ` converts the meta into date even they are not. This PR adds the restriction that will check that if the meta year is greater than 2099 than don't convert into `datetime` format

Closes #2769 

### Changelog Entry

Fixed: Meta values that are not date are converted into date format

### Credits

Props @burhandodhy

2022-06-07 17:40 UTC, felipeelia requested changes

2022-06-07 17:40 UTC, felipeelia commented on includes/classes/Indexable.php
> +			// if year in date is greater than 2099.
@burhandodhy can we rewrite this a bit just to make it clear that it comes from an Elasticsearch limitation? A `@see https://github.com/10up/ElasticPress/issues/2769` can also help developers to find why we have this max.

Beyond that, I wonder if it wouldn't be good to have a filter here, so people could change it if needed. Thoughts?

2022-06-08 09:54 UTC, burhandodhy commented on includes/classes/Indexable.php
> +			// if year in date is greater than 2099.
@felipeelia I have added the new filter `ep_max_year_limit` and also update the comment. Let me know if further changes required.

2022-06-13 20:26 UTC, felipeelia requested changes

2022-06-13 20:26 UTC, felipeelia commented on includes/classes/Indexable.php
> +			$max_year = apply_filters( 'ep_max_year_limit', 2099 );
This is looking better @burhandodhy, thanks. Some changes are still needed though.
1. The `Use default...` text and the `@see` tag should be part of the "docblock", i.e., instead of having `//` in front of them, they should be part of the comment with `/**`. [Here](https://github.com/10up/ElasticPress/blob/00d697614a561e337b388a472de32697b3dd3c1a/includes/classes/Feature/Search/Weighting.php#L144) is an example of a docblock with an additional comment.
2. Can you please add a `@since` tag with `4.2.1`?
Thanks!

2022-06-14 05:54 UTC, burhandodhy commented on includes/classes/Indexable.php
> +			$max_year = apply_filters( 'ep_max_year_limit', 2099 );
Thanks for pointing out the mistake. Feeback is addressed.

2022-06-14 14:03 UTC, merged