Add new filter ep_disable_autosave_sync and enable autosave sync for protected_content feature
10up/ElasticPress pull request #2861
Opened 2022-06-24 19:54 UTC by rebeccahum

### Description of the Change

Problem: When a user has the `protected_content` feature enabled, and they work on a draft but they never hit "Save draft" and instead, rely on the WordPress autosave, it won't show up in the Draft post listing screen (/wp-admin/edit.php?post_status=draft&post_type=post):

<img width="1489" alt="Screen Shot 2022-06-24 at 1 43 00 PM" src="https://user-images.githubusercontent.com/16962021/175656754-625f8270-aa5c-474c-8d79-2c81eacdc387.png">

This is because it never gets synced, as we disable it here:

https://github.com/10up/ElasticPress/blob/aaf2a3342b61c5df958f874cfa1fb434c244201f/includes/classes/Indexable/Post/SyncManager.php#L284-L289

This PR does two things:
- Introduces the `ep_disable_autosave_sync` filter 
- Returns false for the aforementioned filter when the `protected_content` feature is enabled

### Alternate Designs

I'm not sure if it would be beneficial to pass in the `__FUNCTION__` for the second parameter during `apply_filters()` if one wanted to customize disabling the autosave sync on function-basis, since we have `action_set_object_terms`, `action_sync_on_update`, etc. to make it more granular:

```
		if ( apply_filters( 'ep_disable_autosave_sync', true, __FUNCTION__ ) ) {
			if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) {
				// Bypass saving if doing autosave
				// @codeCoverageIgnoreStart
				return;
				// @codeCoverageIgnoreEnd
			}
		}
```

Curious on your thoughts @felipeelia for that.

### Possible Drawbacks

N/A.

### Verification Process

1) Enable the `protected_content` feature
2) Start drafting a new post and wait for WordPress to autosave
3) Go to the Draft post listing screen at `/wp-admin/edit.php?post_status=draft&post_type=post` and expect to see the autosaved draft

### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/10up/.github/blob/trunk/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Changelog Entry

Fixed: autosaved drafts not showing up in draft post listing when using protected_content

### Credits

Props @rebeccahum

2022-07-25 13:26 UTC, felipeelia commented
Hey @rebeccahum, I'm finally getting to this one. I like the idea of adding `__FUNCTION__` as a parameter so people can opt out of some scenarios, can you please add that too?

In addition to that, do you think it'd be possible to add some tests? End-to-end tests checking if that works as expected and also does not affect published posts is what I have in mind. Thanks!

2022-08-02 22:57 UTC, rebeccahum commented
@felipeelia Done and done!

2022-08-03 11:21 UTC, felipeelia requested changes

2022-08-03 11:21 UTC, felipeelia commented on tests/cypress/support/commands.js
> +	cy.wait(80000);
@rebeccahum I think this is needed to wait until the auto-draft is saved, right? Instead of adding this amount of time to the overall test time, what do you think about adding a 1-line plugin [here](https://github.com/10up/ElasticPress/tree/develop/tests/cypress/wordpress-files/test-plugins) just to set the `AUTOSAVE_INTERVAL` constant? Then we would enable it at the beginning of the command and disable it right after.

2022-08-03 11:21 UTC, felipeelia commented on includes/classes/Feature/ProtectedContent/ProtectedContent.php
> +		add_filter( 'ep_skip_autosave_sync', '__return_false', 10, 2 );
@rebeccahum any reason to pass `10, 2` here?

2022-08-03 18:50 UTC, rebeccahum commented
@felipeelia Thanks for the feedback, I think I got it working now!

2022-08-05 15:23 UTC, merged