Add E2E for Custom Results Feature
10up/ElasticPress pull request #2871
Opened 2022-06-29 13:27 UTC by burhandodhy

### Description of the Change

Closes #

### Alternate Designs

### Possible Drawbacks

### Verification Process

### Checklist:

- [ ] I have read the [**CONTRIBUTING**](https://github.com/10up/.github/blob/trunk/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Changelog Entry

### Credits

Props @

2022-08-08 15:17 UTC, felipeelia requested changes

2022-08-08 15:17 UTC, felipeelia commented on tests/cypress/integration/features/custom-results.spec.js
> +	});
Can we remove these things before the tests rather than after them? (I've [linked to this](https://docs.cypress.io/guides/references/best-practices#Using-after-or-afterEach-hooks) already in another PR but leaving here to make it easier to find)

2022-08-08 15:17 UTC, felipeelia commented on tests/cypress/integration/features/custom-results.spec.js
> +		});
Do you mind documenting what this is doing on the screen? It is not super clear to me.

2022-08-08 15:17 UTC, felipeelia commented on tests/cypress/integration/features/custom-results.spec.js
> +	it('Can add the post in result and verify the result on search', () => {
This is also not clear to me. Isn't it adding Fantastic as a custom result but with a post that already has that in it? Would it behave differently if the custom result simply failed?

2022-08-11 12:55 UTC, burhandodhy commented on tests/cypress/integration/features/custom-results.spec.js
> +	});
Done

2022-08-11 12:55 UTC, burhandodhy commented on tests/cypress/integration/features/custom-results.spec.js
> +		});
Done

2022-08-11 12:57 UTC, burhandodhy commented on tests/cypress/integration/features/custom-results.spec.js
> +	it('Can add the post in result and verify the result on search', () => {
This creates a new search and adds a custom post on search and than verify the result on frontend

2022-08-12 13:01 UTC, felipeelia commented on tests/cypress/integration/features/custom-results.spec.js
> +		});
Thanks for moving this @burhandodhy! I should've thought about this before but what do you think about deleting these in a wp-cli call?

2022-08-12 13:01 UTC, felipeelia commented on tests/cypress/integration/features/custom-results.spec.js
> +		cy.get('.search-pointers').type('hello world');
Where is this post created @burhandodhy? If it is created by the initial import, do you mind creating it here (and deleting it before running the test again?)

2022-08-12 19:18 UTC, felipeelia approved these changes

2022-08-12 19:26 UTC, merged