Limit WooCommerce integration with ability to allow it
10up/ElasticPress pull request #2914
Opened 2022-08-01 18:45 UTC by MARQAS

### Description of the Change
Filter to allow WooCommerce. It will limit the usage of WooCommerce integration to the places where it is actually needed. 

Closes #2809 

### How to test the Change

### Changelog Entry

> Added - Filter to allow/limit WooCommerce integration
> Changed - `should_integrate_with_query` function

### Credits

Props @MARQAS 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2022-08-08 15:38 UTC, felipeelia requested changes

2022-08-08 15:38 UTC, felipeelia commented on includes/classes/Feature/WooCommerce/WooCommerce.php
> +		if ( method_exists( $query, 'is_search' ) && ! $query->is_search() && empty( $query->query_vars['s'] ) ) {
@MARQAS I think we can tweak this a little bit. What do you think about checking for `$query->query_vars['ep_integrate']` right before this if? I think we will want to keep running through ES queries that have ep_integrate set. That change will also reflect on some of the changes you made for tests.

Do you think you could write in which scenarios we would expect the query to run through ES or not, and then write unit tests to test that?

2022-08-24 16:20 UTC, felipeelia requested changes

2022-08-24 16:20 UTC, felipeelia commented on includes/classes/Feature/WooCommerce/WooCommerce.php
>  		}
We will need to reverse the order of these two ifs to reflect how we have it in the other places: first, we check if `is_integrated_request`, and after we check for `ep_integrate`. In the current codebase, an AJAX request needs both `ep_integrate` and its own filter `ep_integrate...` to run through ElasticPress.

2022-08-24 16:20 UTC, felipeelia commented on includes/classes/Feature/WooCommerce/WooCommerce.php
>  		}
This needs to be moved to before any `return true;` we may have, as things won't work properly in their API request.

2022-08-24 16:20 UTC, felipeelia commented on includes/classes/Feature/WooCommerce/WooCommerce.php
> +			 */
Let's add a `@since` tag here :)

2022-08-24 16:20 UTC, felipeelia commented on tests/php/features/TestWooCommerce.php
>  		$query = new \WP_Query( $args );
It seems we should change this test entirely: we actually should make sure it will NOT be integrated with EP if it doesn't need it, right?

2022-08-24 16:20 UTC, felipeelia commented on tests/php/features/TestWooCommerce.php
>  					'terms'    => array( 'cat' ),
Same here.

2022-08-24 16:22 UTC, felipeelia commented
@MARQAS before we merge this one we will need a list of real scenarios where we would expect the feature to integrate or not with Elasticsearch. Then that will need to become proper tests. Can you please work on that? Thanks.

2022-09-19 22:46 UTC, oscarssanchez commented
https://github.com/10up/ElasticPress/pull/2914/commits/f66b88011ac471fd8fa013025024fc641626b443 looks good but am not sure if the two instances of ep_integrate removed from tests is all we need. Did we create the list of scenarios @MARQAS ?

2022-10-12 13:57 UTC, felipeelia commented
@MARQAS I've created a new sheet in our doc with a format I think will make things easier for us to understand. Can you please let me know when you have that completely filled? Feel free to add any new lines/scenarios you think I missed.
After we have that complete, we can plan to write tests for each scenario. Thanks!

2023-01-20 14:59 UTC, felipeelia requested changes

2023-01-20 14:59 UTC, felipeelia commented on includes/classes/Feature/WooCommerce/WooCommerce.php
> +		if ( method_exists( $query, 'is_search' ) && ! $query->is_search() && empty( $query->query_vars['s'] ) ) {
[question] The `is_search()` method is available since WP 3.1.0. Is there any reason why we are checking if it exists?

2023-01-20 14:59 UTC, felipeelia commented on includes/classes/Feature/WooCommerce/WooCommerce.php
> +			 * @since  4.4.0
We will need to update this to 4.5.0

2023-02-24 14:20 UTC, felipeelia commented
Closing this in favor of (the already merged) #3259

2023-02-24 14:20 UTC, closed without merging