Display last sync info in site health screen
10up/ElasticPress pull request #2917
Opened 2022-08-02 11:26 UTC by oscarssanchez

### Description of the Change

This PR adds the sync info in the site health screen

Closes #2856

Closes #

### How to test the Change

### Changelog Entry

> Added - Display last sync info in site health screen

### Credits

Props @oscarssanchez , @felipeelia 

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2022-08-02 11:32 UTC, felipeelia commented on includes/classes/SyncManager.php
> +		$sync_info = \ElasticPress\IndexHelper::factory()->get_last_index();
As we already are in the ElasticPress namespace, do we really need the `\ElasticPress\` part here, @oscarssanchez ?

2022-08-02 11:33 UTC, felipeelia commented
@oscarssanchez did you test this if the last sync threw some errors? The following snippet will likely throw errors related to the field limits, if you need:
```
add_filter(
	'ep_prepare_meta_data',
	function( $post_meta, $post ) {
		for ( $i = 0; $i < 100; $i++ ) {
			$post_meta[ "test_meta_{$i}_title_{$post->ID}" ] = 'Lorem';
			$post_meta[ "test_meta_{$i}_body_{$post->ID}" ]  = 'Ipsum';
		}
		return $post_meta;
	},
	10,
	2
);
```

2022-08-09 01:35 UTC, oscarssanchez commented
> @oscarssanchez did you test this if the last sync threw some errors? The following snippet will likely throw errors related to the field limits, if you need:
> 
> ```
> add_filter(
> 	'ep_prepare_meta_data',
> 	function( $post_meta, $post ) {
> 		for ( $i = 0; $i < 100; $i++ ) {
> 			$post_meta[ "test_meta_{$i}_title_{$post->ID}" ] = 'Lorem';
> 			$post_meta[ "test_meta_{$i}_body_{$post->ID}" ]  = 'Ipsum';
> 		}
> 		return $post_meta;
> 	},
> 	10,
> 	2
> );
> ```

Yes errors seem to be logged correctly as well.

2022-08-10 19:23 UTC, felipeelia requested changes
Overall it looks good @oscarssanchez. Although it is very developer-ish information, I still think we could use some better labels there. `Total time` instead of `total_time`, for example.

Can we have a new array mapping those labels to actual terms? It would obviously default to the label itself when no real term is found.

2022-08-10 19:23 UTC, felipeelia commented on includes/classes/SyncManager.php
> +			$debug_info['ep_last_sync']['fields'][ sanitize_title( $label ) ] = [
@oscarssanchez is there any reason why we are sanitizing it here and not in the line below?

2022-08-10 19:23 UTC, felipeelia commented on includes/classes/SyncManager.php
> +
@oscarssanchez I am not sure if SyncManager.php would be the best file to place this code. Did you consider creating a new class under the includes/classes/Screen folder and calling it in Screen.php (like we have for Sync)? We could create a separate HealthInfo as well.

2022-08-10 19:23 UTC, felipeelia commented on tests/cypress/integration/general.spec.js
> +		).should('contain.text', 'end_time_gmt');
As this is the same info we have in end_date_time, I think we can remove this one. One thing I'd like to see added to the `ep_last_index` is the method used to sync (wp-cli or dashboard, for example). Likely a change that needs to happen in IndexHelper::update_last_index.

2022-08-25 13:37 UTC, merged