Add E2E tests for WooCommerce
10up/ElasticPress pull request #2923
Opened 2022-08-04 08:47 UTC by burhandodhy

### Description of the Change
This PR adds new test cases for the WooCommerce feature.

### Credits

Props @burhandodhy 

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2022-08-08 14:59 UTC, felipeelia requested changes

2022-08-08 14:59 UTC, felipeelia commented on tests/cypress/integration/features/woocommerce.spec.js
> +		cy.get('#search-submit').click();
Could we create an order here? That would also help to check if newly created orders are properly indexed.

2022-08-08 14:59 UTC, felipeelia commented on tests/cypress/integration/features/woocommerce.spec.js
> +		cy.get('.woocommerce-orders-table tbody tr').should('have.length', 3);
I see this works but shouldn't we create orders with other users too? Not sure how we have that in the initial import.

2022-08-08 14:59 UTC, felipeelia commented on tests/cypress/integration/features/woocommerce.spec.js
> +	it('Can a user only see his orders on the My Account Order page', () => {
can we have it as `can not display other users' orders on the My Account Order page`?

2022-08-24 17:22 UTC, felipeelia requested changes

2022-08-24 17:22 UTC, felipeelia commented on tests/cypress/integration/features/woocommerce.spec.js
> +		);
As the name of the test is `Can not display other users orders on the My Account Order page` shouldn't we log in using a different user and check (1) that EP is used and (2) the order is not displayed?

2022-08-24 17:22 UTC, felipeelia commented on tests/cypress/integration/features/woocommerce.spec.js
> +		cy.get('#post-search-input').type(`${userData.firstName} ${userData.lastName}{enter}`);
We could expand this test a bit. Instead of simply searching for the user name, let's also search for order IDs, billing and shipping info, and items: https://github.com/10up/ElasticPress/blob/develop/includes/classes/Feature/WooCommerce/WooCommerce.php#L411

2022-08-25 07:32 UTC, burhandodhy commented on tests/cypress/integration/features/woocommerce.spec.js
> +		);
Done. The reason it was not done before was that we had some dummy orders that were linked with the admin user.

2022-08-25 07:32 UTC, burhandodhy commented on tests/cypress/integration/features/woocommerce.spec.js
> +		cy.get('#post-search-input').type(`${userData.firstName} ${userData.lastName}{enter}`);
Done

2022-09-08 16:35 UTC, felipeelia requested changes

2022-09-08 16:35 UTC, felipeelia commented on tests/cypress/integration/features/woocommerce.spec.js
> +		);
Just to be sure we are not capturing an autosuggest template query or similar, can we check for `shop_order` in this query?

2022-09-08 16:35 UTC, felipeelia commented on tests/cypress/integration/features/woocommerce.spec.js
> +		);
same, can we check for `shop_order` on this one as well?

2022-09-08 16:35 UTC, felipeelia commented on tests/cypress/integration/features/woocommerce.spec.js
>  });
@burhandodhy can we bring to this file the test we have for Product variations skus?

2022-09-15 16:58 UTC, merged