Improve wpcli commands test coverage
10up/ElasticPress pull request #2926
Opened 2022-08-04 11:55 UTC by burhandodhy

### Description of the Change

This PR adds more test for the wpcli commands.

### Credits

Props @burhandodhy 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests pass.

2022-08-08 14:56 UTC, felipeelia requested changes

2022-08-08 14:56 UTC, felipeelia commented on tests/cypress/integration/wp-cli.spec.js
> +			});
@burhandodhy I may be wrong but I don't think this is testing anything different than the regular index. Ultimately `--static-bulk` will prevent EP to try to sync sending several requests per batch of ES documents, i.e., if per-page=500:
- Without `--static-bulk` EP will fetch 500 posts from the database, split that number of posts into small groups and send different requests
- With it, EP will fetch 500 posts from the DB and send ALL of them at once.

One way to test would be checking if the `ep_after_bulk_index` action OR the `ep_after_bulk_index_dynamically` actions were fired. Another one could be checking the number of requests fired.

2022-08-08 14:56 UTC, felipeelia commented on tests/cypress/integration/wp-cli.spec.js
> +		cy.wpCli('wp elasticpress get-indexes --pretty').its('code').should('equal', 0);
Any chance we check for new lines and tabs here? It would be the main difference generated by the `--pretty` flag.

2022-08-08 14:56 UTC, felipeelia commented on tests/cypress/integration/wp-cli.spec.js
> +	it('Can stop the indexing operation', () => {
@burhandodhy we probably could mix these two tests in just one, let's say `it('Can stop the sync operation and clear it')`, and then move the clear-index call to the bottom of the second test, replacing the `delete_option( 'ep_index_meta' ); delete_transient( 'ep_sync_interrupted');` call.

2022-08-12 12:32 UTC, burhandodhy commented on tests/cypress/integration/wp-cli.spec.js
> +		cy.wpCli('wp elasticpress get-indexes --pretty').its('code').should('equal', 0);
Done

2022-08-12 12:32 UTC, burhandodhy commented on tests/cypress/integration/wp-cli.spec.js
> +	it('Can stop the indexing operation', () => {
Done

2022-08-12 12:33 UTC, burhandodhy commented on tests/cypress/integration/wp-cli.spec.js
> +			});
Done. Created a test plugin and used `ep_after_bulk_index` action to log the message

2022-08-12 12:52 UTC, felipeelia commented on tests/cypress/integration/wp-cli.spec.js
> +			cy.activatePlugin('fake-log-messages');
do you mind deactivating the plugin after the test @burhandodhy ?

2022-08-12 19:17 UTC, felipeelia approved these changes

2022-08-12 19:17 UTC, merged