Add E2E tests for terms feature
10up/ElasticPress pull request #2931
Opened 2022-08-08 10:52 UTC by burhandodhy

### Description of the Change

This PR adds the E2E tests for the terms feature.

### Credits

Props @burhandodhy 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests pass.

2022-08-08 14:12 UTC, felipeelia requested changes
Overall this looks great @burhandodhy! I left some comments and requested some changes but please let me know if you have any concerns or a different approach in mind.

2022-08-08 14:12 UTC, felipeelia commented on tests/cypress/integration/features/terms.spec.js
> +	it('Can searching a term in the admin dashboard use Elasticsearch', () => {
@burhandodhy can we rephrase it to `Can search a term in the admin dashboard using Elasticsearch`?

2022-08-08 14:12 UTC, felipeelia commented on tests/cypress/integration/features/terms.spec.js
> +		cy.get('.wp-list-table tbody tr').should('have.length', 1).should('contain.text', term);
@burhandodhy can we check if the results came from Elasticsearch?

2022-08-08 14:12 UTC, felipeelia commented on tests/cypress/integration/features/terms.spec.js
> +		cy.get('.wp-list-table tbody').should('contain.text', 'No categories found');
@burhandodhy can we check if the results came from Elasticsearch?

2022-08-08 14:12 UTC, felipeelia commented on tests/cypress/integration/features/terms.spec.js
> +		);
@burhandodhy How could we make sure this query is really the one we are looking for?

2022-08-08 14:12 UTC, felipeelia commented on tests/cypress/integration/features/terms.spec.js
> +		const searchTerm = 'classic';
@burhandodhy I think this comes from the default content being imported at the beginning of the tests, is that right? If so, can we create a term during the test? The initial import slows things down quite a bit and I'm planning to remove that eventually.

2022-08-08 14:12 UTC, felipeelia commented on tests/cypress/integration/features/terms.spec.js
> +		});
@burhandodhy although it sometimes can be counterintuitive, we should actually clean things created by tests *before* the tests: https://docs.cypress.io/guides/references/best-practices#Using-after-or-afterEach-hooks (the docs mention the hooks, but the idea remains the same.)

We could use something like we are using for users here: https://github.com/10up/ElasticPress/blob/develop/tests/cypress/integration/indexables/user.spec.js#L9

Thoughts?

2022-08-08 14:12 UTC, felipeelia commented on tests/cypress/integration/features/terms.spec.js
> +		cy.get('.wp-list-table tbody tr .row-title').should('contain.text', 'The Most Fun Thing');
@burhandodhy can we check if the results came from Elasticsearch?

2022-08-08 14:12 UTC, felipeelia commented on tests/cypress/integration/features/terms.spec.js
> +	it('Can a child term be updated when a parent term is deleted', () => {
@burhandodhy can we rephrase this to something like `can update a child term when a parent term is deleted`? The intent is to come up with a phrase where `it` is the app doing something.

2022-08-08 14:12 UTC, felipeelia commented on tests/cypress/support/commands.js
> +Cypress.Commands.add('createTaxonomy', (data) => {
@burhandodhy great improvement here, thanks!

2022-08-09 06:25 UTC, burhandodhy commented on tests/cypress/integration/features/terms.spec.js
> +		});
@felipeelia as we are planning to get the rid of all the dummy data. Is it okay to delete all the terms by using the following command `wp term list post_tag --field=term_id | xargs wp term delete post_tag` in the before hook?

2022-08-11 14:57 UTC, burhandodhy commented on tests/cypress/integration/features/terms.spec.js
> +	it('Can searching a term in the admin dashboard use Elasticsearch', () => {
Done

2022-08-11 14:57 UTC, burhandodhy commented on tests/cypress/integration/features/terms.spec.js
> +		cy.get('.wp-list-table tbody tr').should('have.length', 1).should('contain.text', term);
Done

2022-08-11 14:57 UTC, burhandodhy commented on tests/cypress/integration/features/terms.spec.js
> +		cy.get('.wp-list-table tbody').should('contain.text', 'No categories found');
Done

2022-08-11 14:59 UTC, burhandodhy commented on tests/cypress/integration/features/terms.spec.js
> +		);
Valid point. I changed the test and now we are looking for the search term in the Elasticsearch result.

2022-08-11 14:59 UTC, burhandodhy commented on tests/cypress/integration/features/terms.spec.js
> +		const searchTerm = 'classic';
Done. Created new term.

2022-08-11 14:59 UTC, burhandodhy commented on tests/cypress/integration/features/terms.spec.js
> +		cy.get('.wp-list-table tbody tr .row-title').should('contain.text', 'The Most Fun Thing');
Done

2022-08-11 14:59 UTC, burhandodhy commented on tests/cypress/integration/features/terms.spec.js
> +	it('Can a child term be updated when a parent term is deleted', () => {
Done

2022-08-11 15:00 UTC, burhandodhy commented on tests/cypress/integration/features/terms.spec.js
> +		});
Thanks for suggestion. I moved it to after hook

2022-08-12 19:39 UTC, felipeelia requested changes

2022-08-12 19:39 UTC, felipeelia commented on tests/cypress/integration/features/terms.spec.js
> +		}).should('contain.text', 'Sync complete');
@burhandodhy let's also check if the mapping was sent here, please. You can see how we are doing it for the WooCommerce feature [here](https://github.com/10up/ElasticPress/blob/develop/tests/cypress/integration/features/woocommerce.spec.js#L32)

2022-08-12 19:39 UTC, felipeelia commented on tests/cypress/integration/features/terms.spec.js
> +	});
@burhandodhy Can we move that to the before hook and use wp-cli to clean it up? With the change made on #2944 we should be able to call nested wp-cli commands now.

2022-08-12 19:39 UTC, felipeelia commented on tests/cypress/support/commands.js
> +Cypress.Commands.add('createTaxonomy', (data) => {
@burhandodhy actually this was wrongly named before. Do you mind updating it to `createTerm`?

2022-08-15 13:25 UTC, burhandodhy commented on tests/cypress/integration/features/terms.spec.js
> +		});
Done.

2022-08-15 13:25 UTC, burhandodhy commented on tests/cypress/integration/features/terms.spec.js
> +		}).should('contain.text', 'Sync complete');
Done

2022-08-15 18:54 UTC, felipeelia approved these changes

2022-08-15 18:54 UTC, merged