E2E tests for Comments Feature
10up/ElasticPress pull request #2955
Opened 2022-08-19 15:09 UTC by burhandodhy

### Description of the Change

Add E2E tests for Comments Feature

### Credits

Props @burhandodhy 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests pass.

2022-08-24 17:17 UTC, felipeelia requested changes
@burhandodhy I left some comments, feel free to reach out via slack if I missed something obvious here. We will need to test this feature with Protected Content enabled as well (those tests will likely live in the `protected-content.spec.js` file. Are you planning to tackle that in a separate PR?

2022-08-24 17:17 UTC, felipeelia commented on tests/cypress/integration/features/comments.spec.js
> +	});
Any reason why we are not testing that in the previous test?

2022-08-24 17:17 UTC, felipeelia commented on tests/cypress/integration/features/comments.spec.js
> +	it('Can sync comments if approved manually', () => {
Is there any reason why we don't simply approve the comment created in the previous test?

2022-08-25 07:43 UTC, burhandodhy commented on tests/cypress/integration/features/comments.spec.js
> +	it('Can sync comments if approved manually', () => {
The main idea is to keep each test independent.

2022-08-25 07:45 UTC, burhandodhy commented on tests/cypress/integration/features/comments.spec.js
> +	});
We can do it, but I think keeping the separate test makes more sense

2022-08-25 11:29 UTC, felipeelia commented on tests/cypress/integration/features/comments.spec.js
> +	});
Actually that does make sense for unit tests, for e2e tests we need to think about performance as well. Cypress's Best Practices guide has a really good text about that: https://docs.cypress.io/guides/references/best-practices#Creating-tiny-tests-with-a-single-assertion
Basically, it would indeed make sense to keep separate tests if you were testing something after deleting the comment. If you are deleting that to create a new one with the same info, we could reuse that, right?

2022-08-25 11:29 UTC, felipeelia commented on tests/cypress/integration/features/comments.spec.js
> +	it('Can sync comments if approved manually', () => {
same as above

2022-08-26 07:31 UTC, burhandodhy commented on tests/cypress/integration/features/comments.spec.js
> +	});
Thank you for pointing me in the right direction. I updated the tests.

2022-09-08 17:07 UTC, merged