Support customizing the template for search results in Instant Results
10up/ElasticPress pull request #2959
Opened 2022-08-23 16:23 UTC by JakePT

### Description of the Change
WIP

Closes #2527

### How to test the Change
WIP

### Changelog Entry
> Added - `elasticpress.InstantResults.Result` JavaScript filter for filtering the component used for Instant Results search results.

### Credits
Props @JakePT 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2022-09-15 17:52 UTC, felipeelia requested changes
@JakePT in addition to my comments, we also need to fix a conflict in theme-integration.md. Do you mind handling that? Thanks

2022-09-15 17:52 UTC, felipeelia commented on assets/js/instant-results/components/common/result.js
> + * @hook elasticpress.InstantResults.Result
@JakePT Instead of disabling the rule, I'd prefer setting it as WooCommerce is doing [here](https://github.com/woocommerce/woocommerce/blob/8952dac7c02a113e80b97d5e57d0eb184796f22a/packages/js/eslint-plugin/configs/recommended.js#L32). One interesting thing on that repo is how they are using `@filter` instead of `@hook` [here](https://github.com/woocommerce/woocommerce/blob/feba6a8dcd55d4f5c7edc05478369c76df082293/plugins/woocommerce-admin/client/analytics/report/revenue/config.js#L20), for example.

I know the decision on this will probably be influenced by the new doc generator we are going to use but I'm curious to hear your thoughts on which would be the best one.

FWIW, this is how I had our `.eslintrs.js` so I didn't need the `eslint-disable jsdoc/check-tag-names` line:
```
const defaultEslintrc = require('10up-toolkit/config/.eslintrc');

module.exports = {
	...defaultEslintrc,
	rules: {
		'jsdoc/check-tag-names': [
			'error',
			{
				definedTags: ['jest-environment', 'filter', 'action', 'slotFill', 'scope'],
			},
		],
	},
};
```

2022-09-15 17:52 UTC, felipeelia commented on docs/theme-integration.md
> +```
@JakePT could we have at least this simpler example in "plain" JS as well? WordPress core documentation makes it available on both ways in some places ([here](https://developer.wordpress.org/block-editor/reference-guides/filters/block-filters/#editor-blockedit), for example) and that might lower the barrier for new developers.

Also, can we make that first line ` ```js ` so GitHub understands its JavaScript? (I imagined GH would detect that automatically but it doesn't seem to be the case.)

2022-09-16 16:21 UTC, JakePT commented on assets/js/instant-results/components/common/result.js
> + * @hook elasticpress.InstantResults.Result
@felipeelia I've:

- Updated `@hook` to `@filter`.
- Updated .eslintrc to accept `@filter`.
- Updated `@since` version.
- Resolved merge conflict in `theme-integration.md`.

Still to do:

- Add E2E tests (it might be good to get #2851 done first).

2022-09-16 16:21 UTC, JakePT commented on docs/theme-integration.md
> +```
@felipeelia I have added `js` to the code blocks but still need to add non-JSX examples.

2022-10-04 03:58 UTC, JakePT commented on docs/theme-integration.md
> +```
@felipeelia I've added non-JSX documentation.

2022-10-04 03:59 UTC, JakePT commented on assets/js/instant-results/components/common/result.js
> + * @hook elasticpress.InstantResults.Result
@JakePT I have added an E2E test for the filter.

2022-10-11 11:48 UTC, merged