Migrate Autosuggest filters to proper WordPress hooks
10up/ElasticPress pull request #2983
Opened 2022-09-05 07:48 UTC by JakePT

### Description of the Change
Migrates the custom 'filter' functions in Autosuggest to use proper WordPress hooks. Existing uses of filter functions are applied as callbacks to the new hooks from a back-compat file.

Closes #2961

### How to test the Change
WIP

### Changelog Entry
WIP

### Credits

Props @JakePT

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2022-09-05 07:50 UTC, JakePT commented on assets/js/autosuggest/back-compat.js
> +	addFilter('ep.Autosuggest.data', 'ep/epDatafilter', window.epDatafilter);
These callback names should probably reflect that they are for backwards compatibility.

2022-09-05 07:51 UTC, JakePT commented on assets/js/autosuggest/index.js
>  			let query = buildSearchQuery(searchText, placeholder, queryJSON);
`buildSearchQuery` should probably just return a parsed value.

2022-09-13 08:52 UTC, JakePT commented on assets/js/autosuggest/index.js
>  			let query = buildSearchQuery(searchText, placeholder, queryJSON);
buildSearchQuery is publicly exposed so changing the return value would break compatibility.

2022-09-16 12:23 UTC, felipeelia requested changes

2022-09-16 12:23 UTC, felipeelia commented on assets/js/autosuggest/index.js
> +		 * @since 4.4.0
@JakePT we can ship this one in 4.3.1, do you mind changing the `@since` tag? Also, with the comment I made in the Instant Result PR, we will probably have to tweak the `@hook` here as well (or at least remove the `jsdoc/check-tag-names` disable.)

2022-09-16 15:36 UTC, JakePT commented on assets/js/autosuggest/index.js
> +		 * @since 4.4.0
@felipeelia Done.

2022-09-22 17:08 UTC, merged