WIP: Add Comments block.
10up/ElasticPress pull request #2986
Opened 2022-09-06 04:42 UTC by JakePT

### Description of the Change
Adds a Block version of the Comments widget.

Closes #2972

### How to test the Change
WIP

### Changelog Entry
WIP

### Credits
@JakePT 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2022-10-11 18:12 UTC, felipeelia commented
@JakePT It seems e2e tests are not passing. Do you mind checking them so we can merge this PR? It may be worth giving a look at the solutions we've implemented to the intermittent failures we had for facets [here](https://github.com/10up/ElasticPress/pull/3053/files).

2022-11-07 12:30 UTC, felipeelia requested changes
@JakePT this looks great. Do you mind addressing the minor issues I highlighted before we merge it? Thanks!

2022-11-07 12:30 UTC, felipeelia commented on assets/js/blocks/comments/block.json
> +	"editorScript": "file:/../../../../dist/js/comments-block-script.js",
@JakePT As we are calling i18n functions in this script, we also need to give it a handle and manually call wp_set_script_translations for it too (yes, WP does not behave as it should.) See [this docblock](https://github.com/10up/ElasticPress/blob/develop/includes/classes/Feature/Facets/Types/Meta/Block.php#L103) for additional context. Do you mind making this change before we can merge it? Thanks!

2022-11-07 12:30 UTC, felipeelia commented on includes/classes/Feature/Comments/Comments.php
> +	}
Any particular reason to make this a static method? Also, can we please add a `@since` to it, if it is really needed?

2022-11-07 12:30 UTC, felipeelia commented on includes/classes/Feature/Comments/Comments.php
> +	 * @return array Array of post type kabeks keyed by post type.
s/kabeks/labels/ :)

2022-11-07 12:30 UTC, felipeelia commented on tests/cypress/integration/features/comments.cy.js
> +		 * Verify the page comments block has the exdpected markup and returns
It seems we have some `exdpected` instead of `expected` in these comments. Do you mind fixing it, please?

2022-11-08 03:39 UTC, JakePT commented on assets/js/blocks/comments/block.json
> +	"editorScript": "file:/../../../../dist/js/comments-block-script.js",
@felipeelia editorScript creates a script handle, which is what I used for wp_localize_script, so I just set script translations with that handle. Will that work?

2022-11-08 03:39 UTC, JakePT commented on includes/classes/Feature/Comments/Comments.php
> +	}
@felipeelia I doesn't have any dependency on `$this` so a static method seemed appropriate. I've now added the `@since` tag.

2022-11-08 03:39 UTC, JakePT commented on includes/classes/Feature/Comments/Comments.php
> +	 * @return array Array of post type kabeks keyed by post type.
@felipeelia Fixed.

2022-11-08 03:39 UTC, JakePT commented on tests/cypress/integration/features/comments.cy.js
> +		 * Verify the page comments block has the exdpected markup and returns
@felipeelia Fixed.

2022-11-08 20:08 UTC, felipeelia commented on assets/js/blocks/comments/block.json
> +	"editorScript": "file:/../../../../dist/js/comments-block-script.js",
Unfortunately, no. I've changed that part of the code so i18n/l10n is possible.

2022-11-09 12:06 UTC, merged