Add filter to remove unavailable terms from facet
10up/ElasticPress pull request #2989
Opened 2022-09-06 13:38 UTC by burhandodhy

### Description of the Change

This PR introduces the new filter `ep_facet_search_terms` that allows filtering the list of terms in Fact. By using this filter, the user can remove the unavailable terms from the facet. Previously suggested [solution](https://github.com/10up/ElasticPress/issues/2760#issuecomment-1144889783) has an issue that shows the search box even the available terms are lower than the threshold. 

Example: The below code will remove the unavailable terms from facet 

```
add_filter( 'ep_facet_search_terms', function ( $terms, $taxonomy ) {

	$filtered_terms = array_filter( $terms, function( $term ) {
		return $term->count > 0 ;
	} );

	return $filtered_terms;
}, 10, 2 );
```

Closes #2760 

### How to test the Change

Add the above code in theme functions.php
Add the Facet block in widgets
Search for any term and it will only show those terms which are available.

### Changelog Entry

> Added - `ep_facet_search_terms` filter to filter the Facet terms

### Credits

Props @burhandodhy 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2022-09-06 13:54 UTC, felipeelia requested changes

2022-09-06 13:54 UTC, felipeelia commented on includes/classes/Feature/Facets/Types/Taxonomy/Renderer.php
> +		$terms_by_slug = apply_filters( 'ep_facet_search_terms', $terms_by_slug, $taxonomy );
@burhandodhy can we please add `@since 4.4.0` on this one? Also, as we now have a meta facet as well, a probably better name would be `ep_facet_taxonomy_terms` (not sure if we want to include "search" on this one, what do you think?)

2022-09-06 13:54 UTC, felipeelia commented on includes/classes/Feature/Facets/Types/Taxonomy/Renderer.php
> +				foreach ( $terms_by_slug as $term ) :
Are you sure about this change? It seems we would lose the tree-organization made on parent/child categories (also, `$terms` doesn't seem to be used anywhere else.)

2022-09-07 11:17 UTC, burhandodhy commented on includes/classes/Feature/Facets/Types/Taxonomy/Renderer.php
> +		$terms_by_slug = apply_filters( 'ep_facet_search_terms', $terms_by_slug, $taxonomy );
@since added. The other filters in same file do have the "search" but I think we should go without it.

2022-09-07 11:17 UTC, burhandodhy commented on includes/classes/Feature/Facets/Types/Taxonomy/Renderer.php
> +				foreach ( $terms_by_slug as $term ) :
Thanks. I totally missed that. Code updated.

2022-09-15 18:48 UTC, felipeelia approved these changes

2022-09-16 12:06 UTC, merged