Adds support for searching shop_subscriptions #2867
10up/ElasticPress pull request #3029
Opened 2022-09-27 23:17 UTC by ecaron

### Description of the Change
This change expands the admin search functionality to work on shop_subscriptions just like it does on shop_orders today, expanding on the [WooCommerce subscription-core](https://github.com/Automattic/woocommerce-subscriptions-core) functionality.

The behavior is just like `shop_order`, where it detects if the searched post_type is `shop_subscription`, and then it hijacks the behavior to route the search through Elasticsearch rather than WordPress' database.

Closes #2867

### How to test the Change

1. Install any plugin that leverages [WooCommerce subscription-core](https://github.com/Automattic/woocommerce-subscriptions-core)
2. Add a subscription
3. Within the [search interface](/wp-admin/edit.php?post_type=shop_subscription), do a search with & without ElasticPress enabled - the search results will be the same (albeit ElasticPress' results will return much faster)

### Changelog Entry
> Changed - Admin search has been expanded to work on shop_subscription in addition to existing shop_order

### Credits
Props @ecaron

### Checklist:
- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests pass.

2022-10-06 22:16 UTC, ecaron commented
@felipeelia Any insight on what would be neeed to get this reviewed/merged?

2022-10-17 18:10 UTC, ecaron commented
@felipeelia Could you elaborate on what "needs discussion" means, so I can do the legwork to provide context? Or is it just an internal flag for the 10Up core team?

2022-10-17 18:23 UTC, felipeelia commented
Hey @ecaron, it is just a flag we use to bring it to our internal syncs. I'll get back to you here once we have anything new to share. Thanks for reaching out!

2022-10-18 16:53 UTC, felipeelia commented
Hey @ecaron, we've talked internally and as this is not strictly related to WooCommerce's core, the best place for it is actually as a subfeature in [ElasticPress Labs](https://github.com/10up/ElasticPressLabs) (there we maintain compatibility with Co-Authors Plus, for example.)

To have that added to EP Labs, the code will be a bit bigger but if you want to give that a try, it would be great! Otherwise, we will try to address it as soon as possible. Thanks!

2022-10-21 13:39 UTC, ecaron commented
I understand. I'll create a PR for this as a subfeature to ElasticPress Labs. [I started with this PR](https://github.com/10up/ElasticPressLabs/pull/43), but my goal is to have this move to a PR there by EOD.

I'll close this once that PR is opened.

2022-10-21 14:48 UTC, ecaron commented
@felipeelia, to help me understand the direction that you're looking to go and likely to approve, are you suggesting:

## Option 1 - Isolating everything to ElasticPressLabs
1. Replace the ElasticPress `ep_wp_query_search_cached_posts` action for `disallow_duplicated_query`
2. Replace the ElasticPress `pre_get_posts`  action for `translate_args`
   This would involve a **massive amount** of copy/paste, and likely to cause EPL to fall out of sync with future EP updates
4. Replace the ElasticPress `ep_sync_insert_permissions_bypass` filter for `bypass_order_permissions_check`
5. Replace the ElasticPress `parse_query` action for `maybe_hook_woocommerce_search_fields` and `search_order`
6. Replace the ElasticPress `ep_post_sync_args_post_prepare_meta` filter for `add_order_items_search`
7. Replace the ElasticPress `ep_pc_skip_post_content_cleanup` filter for `keep_order_fields`

## Option 2 - Tweaks to ElasticPress to make hooking from EPL easier
1. Adjust the altered `if` statements in this PR to rely on `do_action`s so external plugins can alter the logic
2. Put the `add_action`s in the EPL feature to properly sideload support for `shop_subscription`

## Option 99 - If the above aren't pleasant ideas for your vision of EPL's future
Since this PR only depends on the MIT-licensed Automattic [woocommerce-subscription-core](https://github.com/Automattic/woocommerce-subscriptions-core), it could be merged in as-is. That repo shows there are other paid plugins that depend on this core, beyond the 2 paid Automattic plugins, so this would inherently bring support for those plugins into ElasticPress core.

2022-10-25 16:18 UTC, felipeelia commented
Hey @ecaron, let's go with option #2, adding in the main plugin the actions and filters needed and then using them in EP Labs. Thanks!

2022-11-06 06:00 UTC, ecaron commented
> Hey @ecaron, let's go with option #2, adding in the main plugin the actions and filters needed and then using them in EP Labs. Thanks!

This PR has been updated to include the hooks and filters mentioned in the aforementioned option 2. PR has been submitted at https://github.com/10up/ElasticPressLabs/pull/44 to leverage them.

2022-11-08 16:49 UTC, felipeelia requested changes
Thanks for the code @ecaron. I've listed some changes we will need before merging this one but nothing major.

2022-11-08 16:49 UTC, felipeelia commented on includes/classes/Feature/WooCommerce/WooCommerce.php
> +		$searchable_post_types = apply_filters( 'ep_woocommerce_admin_searchable_post_types', $searchable_post_types );
Can we create a new method, let's say get_admin_searchable_post_types, and move this apply_filters call there? Something like we do for get_searchable_post_types() already ([here](https://github.com/10up/ElasticPress/blob/4.3.1/includes/classes/Feature/Search/Search.php#L371))

2022-11-08 16:49 UTC, felipeelia commented on includes/classes/Feature/WooCommerce/WooCommerce.php
> +		do_action( 'ep_woocommerce_hook_search_fields' );
Can you please add a `@since` tag here and also pass the $query as a parameter of the action?

2022-11-09 13:59 UTC, felipeelia commented on includes/classes/Feature/WooCommerce/WooCommerce.php
> +		$supported_post_types = apply_filters( 'ep_default_supported_post_types', $post_types );
@ecaron we will need to rename this one too. Something like `ep_woocommerce_default_supported_post_types` to better indicate it is a WooCommerce-specific filter. Also, do you mind removing one of those 2 `.` in the filter description? Thanks

2022-11-09 15:55 UTC, ecaron commented on includes/classes/Feature/WooCommerce/WooCommerce.php
> +		do_action( 'ep_woocommerce_hook_search_fields' );
`@since` tag has been added

2022-11-09 15:55 UTC, ecaron commented on includes/classes/Feature/WooCommerce/WooCommerce.php
> +		$searchable_post_types = apply_filters( 'ep_woocommerce_admin_searchable_post_types', $searchable_post_types );
Nice suggestion. This cleans it up a ton! Updated.

2022-11-09 15:55 UTC, ecaron commented on includes/classes/Feature/WooCommerce/WooCommerce.php
> +		$supported_post_types = apply_filters( 'ep_default_supported_post_types', $post_types );
Renamed and de-dotted.

2022-11-09 17:10 UTC, ecaron commented
@felipeelia The "E2E Test / Cypress - Local" failure seems unrelated to this PR (failing in #3129 and #3068). Do you see this being included in the 4.4.0 work covered under #3129, or should I update the PR to have it target 4.5.0?

2022-11-09 17:16 UTC, felipeelia commented
Hey @ecaron, I'm also keeping an eye on those tests :) . And this will be part of 4.4.0, no need to change anything (I'm just rerunning the tests to see if they unstuck now.) Thanks!

2022-11-09 18:04 UTC, merged

2024-07-11 10:44 UTC, amanfredini76 commented
PROBLEM
https://github.com/10up/ElasticPress/issues/3940
can you reply please? it's urgent

2024-07-11 12:37 UTC, felipeelia commented
@amanfredini76 there is no point in commenting on a Pull Request closed in 2022, let's please keep your problem isolated in that issue.