Fix: Facet returns no result for non-english term
10up/ElasticPress pull request #3031
Opened 2022-09-28 11:30 UTC by burhandodhy

### Description of the Change

This PR fixes the issue where the facet doesn't work when the non-English term is selected. 

Closes #3023 

### How to test the Change

- Create a new category `غير-مصنف`
- Assign some posts to new category
- Go to frontend and select `غير-مصنف` from taxonomy widget
- EP should returns the from `غير-مصنف` category

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability

### Credits

Props @burhandodhy 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2022-10-11 16:36 UTC, felipeelia commented
Facets e2e tests are consistently failing in this one @burhandodhy. Do you mind giving a look before we merge it? Thanks!

2022-10-12 08:27 UTC, burhandodhy commented
> Facets e2e tests are consistently failing in this one @burhandodhy. Do you mind giving a look before we merge it? Thanks!

@felipeelia Tests are fixed. The problem was that the `sanitize_title` function was not a good choice for meta fields and `sanitize_text_field` for taxonomies. So to fix the problem, I introduced the new method `sanitize_callback` in classes. Now every class will have the ability to change the satanize function without effecting the other classes.

2022-10-12 12:35 UTC, felipeelia commented
@burhandodhy after giving this one a deeper look, it seems we might be going in the wrong direction. Instead of fixing the sanitization of the slug, your new code actually showed me we have a different problem:

If we create a post with a meta field with that same value, the meta facet will generate a URL with a different value than the taxonomy:

https://ep-es7.test/?ep_filter_category=%25d8%25ba%25d9%258a%25d8%25b1-%25d9%2585%25d8%25b5%25d9%2586%25d9%2581&ep_meta_filter_my_first_field=%D8%BA%D9%8A%D8%B1-%D9%85%D8%B5%D9%86%D9%81 (see how `ep_filter_category` is different from `ep_meta_filter_my_first_field` but they should be the same.)

Investigating it a little bit, it seems things work well if we use `$term->name` instead of `$term->slug`. Do you mind giving it another look? Feel free to ping me on slack to discuss the best way to move forward.

2022-10-17 17:25 UTC, felipeelia requested changes
@burhandodhy great progress on this one, thanks. I've left yet another comments/suggestions/changes here, let me know your thoughts about it.
One thing that I'm trying to do is to add unit tests for all filters/actions being called. Do you think it would be possible to add unit tests for these new filters as well? Thanks!

2022-10-17 17:25 UTC, felipeelia commented on includes/classes/Feature/Facets/FacetType.php
> +	abstract public function get_sanitize_callback() : string;
@burhandodhy so, given the fact that probably `sanitize_text_field` would be the "default" method, what do you think about making it a concrete method that defaults to sanitize_text_field (with a filter for it as well, like `ep_facet_default_sanitize_callback`?

2022-10-17 17:25 UTC, felipeelia commented on includes/classes/Feature/Facets/Facets.php
> +						'terms' => array_fill_keys( array_map( $sanitize_callback, explode( ',', trim( $value, ',' ) ) ), true ),
I guess we could use the opportunity to refactor this line a bit. Several methods are being called in the same line :)

2022-10-18 10:43 UTC, burhandodhy commented
@felipeelia I made the changes that you requested. I also added the tests for the filters.

2022-10-20 20:55 UTC, felipeelia requested changes
We are almost there, @burhandodhy!

2022-10-20 20:55 UTC, felipeelia commented on tests/php/features/TestFacetTypeMeta.php
> +		};
Can we just make sure we are testing something here? I was thinking of something like:

```suggestion
		$sanitize_function = function ( $function ) {
			$this->assertSame( 'sanitize_text_field', $function );
			return 'sanitize_title';
		};
```

We probably should also test if the filter is being applied in the first place (that `assertSame` wouldn't be called if the filter is not called.) Perhaps a global variable changed inside the filter and tested after the `->get_selected();` call or something similar.

2022-10-20 20:55 UTC, felipeelia commented on tests/php/features/TestFacetTypeMeta.php
> +		$test_meta     = 'This is s test meta';
There is a typo here @burhandodhy but I think we could one step further and actually test a string that needs to be sanitized. What do you think?

2022-10-20 20:55 UTC, felipeelia commented on tests/php/features/TestFacetTypeTaxonomy.php
> +		};
Same as above

2022-10-21 06:45 UTC, burhandodhy commented on tests/php/features/TestFacetTypeMeta.php
> +		};
Done

2022-10-21 06:48 UTC, burhandodhy commented on tests/php/features/TestFacetTypeMeta.php
> +		$test_meta     = 'This is s test meta';
Thank you for pointing it out. @felipeelia we are already testing the sanitized string https://github.com/10up/ElasticPress/pull/3031/files#diff-d36fb3af9a833294f34cf95964cbdc054fb4d401805400564aa71bc8ce01db90R196

2022-10-21 15:19 UTC, felipeelia approved these changes
Thanks for all the hard work on this one @burhandodhy!

2022-10-21 16:24 UTC, merged