Auto sync parent terms
10up/ElasticPress pull request #3145
Opened 2022-11-22 18:43 UTC by MARQAS

### Description of the Change
Auto-sync the parent terms when child terms are selected in the posts

Closes #3105 

### How to test the Change

- Go to WordPress default categories
- Add 2 terms, make one of them child to the other
- Go to WordPress default posts
- Add a new post and link the child term with it
- Edit the parent term slug
- Go to Elasticsearch and check the post document and note that parent slug is also updated

### Changelog Entry

> Fixed - Auto sync issue with parent term
### Credits

Props @MARQAS 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2022-11-23 13:52 UTC, felipeelia commented
@MARQAS a couple of questions:
1. Can we add some unit tests for this?
2. Do we also have the bug when a parent term is deleted? If so, this covers that scenario as well?
3. To increase readability, do you mind wrapping variables in double quote strings with `{}`, like in `"SELECT object_id FROM {$wpdb->term_relationships} WHERE term_taxonomy_id...`
4. Will we have a performance problem if too many posts are associated with child terms?

2022-12-09 13:53 UTC, felipeelia requested changes
@MARQAS do you mind making the suggestions I've added? Just so we keep var names consistent. Thanks!

2022-12-09 13:53 UTC, felipeelia commented on tests/php/indexables/TestPost.php
> +		$test_tag = get_term_by( 'id', $term1['term_id'], $tax_name );
```suggestion
		$term_1_name = rand_str( 32 );
		$term_1      = wp_insert_term( $term_1_name, $tax_name );

		$term_2_name = rand_str( 32 );
		$term_2      = wp_insert_term( $term_2_name, $tax_name, array( 'parent' => $term_1['term_id'] ) );

		wp_set_object_terms( $post->ID, array( $term_2['term_id'] ), $tax_name, true );

		ElasticPress\Elasticsearch::factory()->refresh_indices();

		$test_tag = get_term_by( 'id', $term_1['term_id'], $tax_name );
```

2022-12-09 13:53 UTC, felipeelia commented on tests/php/indexables/TestPost.php
> +		$this->assertEquals( 'Parent Term', $document['terms'][$tax_name][1]['name'] );
```suggestion
		$this->assertEquals( 'parent-term', $document['terms'][ $tax_name ][1]['slug'] );
		$this->assertEquals( 'Parent Term', $document['terms'][ $tax_name ][1]['name'] );
```

2022-12-13 12:10 UTC, MARQAS commented
@felipeelia I have added the changes you asked for along with a notice. I observed that it wasn't showing notice when the parent term was not attached to the posts. 
Steps to reproduce: 

- Add parent and child terms
- Attach child term to the posts
- Make `Content Items per Index Cycle` less than the posts attached to the child term.
- While editing a child term, you can see the notice. 
- But it will not show the notice when editing a parent term. 
- It will only show the notice on the parent term if the posts attached to the parent term are greater than `Content Items per Index Cycle`

With this PR, it will show the notice on the parent term as well if posts associated with one of its child terms are greater than the `Content Items per Index Cycle`

2023-01-20 14:43 UTC, merged