WIP: Orders autosuggest
10up/ElasticPress pull request #3175
Opened 2022-12-02 11:38 UTC by JakePT

### Description of the Change
WIP

### How to test the Change
WIP

### Changelog Entry
WIP

### Credits
WIP

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2023-01-31 17:14 UTC, felipeelia requested changes
@JakePT I left some comments (mostly just thoughts and things we will need to keep track of). Do you mind reaching out to me on slack to share an endpoint I can use to test it? Thanks!

2023-01-31 17:14 UTC, felipeelia commented on includes/classes/Feature/WooCommerce/Orders.php
> + * @package ElasticPress\Feature\WooCommerce
@JakePT do you mind moving the `@since` tag to the file docblock? Also, I guess we can avoid `@packages` at a class level and keep only the file level one. We are currently using different solutions in different places, so let's keep it as simple as possible and change it back if we decide differently later.

2023-01-31 17:14 UTC, felipeelia commented on includes/classes/Feature/WooCommerce/Orders.php
> +		if ( 'shop_order' !== $_GET['post_type'] ) { // phpcs:ignore WordPress.Security.NonceVerification.Recommended
[question] Isn't this throwing a notice in logs if post_type is not in the query string?

2023-01-31 17:14 UTC, felipeelia commented on includes/classes/Feature/WooCommerce/Orders.php
> +			)
thought [non-blocking]: we probably should add some filters here so people can easily change these values.

2023-01-31 17:14 UTC, felipeelia commented on includes/classes/Feature/WooCommerce/Orders.php
> +		$response = Elasticsearch::factory()->remote_request(
It seems `$response` is never used, so can we simply don't assign it to a variable? (Or people will get tempted to add `$response` to the action below but as the request is non-blocking, it will go empty.)

2023-01-31 17:14 UTC, felipeelia commented on includes/classes/Feature/WooCommerce/Orders.php
> +			)
This will also need a filter. If adding it to this PR sounds too early let's capture that need somewhere else.

2023-01-31 17:14 UTC, felipeelia commented on includes/classes/Feature/WooCommerce/Orders.php
> +		update_user_meta( $user_id, 'ep_temporary_token', $token );
We need to delete these during the plugin uninstall. Also, this will eventually expire, right? I didn't find where we are getting a new one if that is the case, sorry :(

2023-02-01 12:34 UTC, JakePT commented on includes/classes/Feature/WooCommerce/Orders.php
> +			)
@felipeelia This query can be filtered using `pre_get_posts` and checking `$query->get( 'ep_order_search_template' )`.

2023-02-01 12:35 UTC, JakePT commented on includes/classes/Feature/WooCommerce/Orders.php
> +		update_user_meta( $user_id, 'ep_temporary_token', $token );
@felipeelia Yeah I'll check with Dustin how we want to do that. At the moment it's treated as if the tokens are permanent.

2023-02-01 12:38 UTC, JakePT commented on includes/classes/Feature/WooCommerce/Orders.php
> +			)
@JakePT So I'm hesitant to allow filtering this for the same reason I was hesitant bout it for Instant Results. I don't think this is mature enough yet. The endpoint does have a filter though, and I believe the host is also filterable (this is largely copied from Instant Results). The Woo formats and statuses also already have their own filters.

2023-02-01 12:43 UTC, JakePT commented on includes/classes/Feature/WooCommerce/Orders.php
> + * @package ElasticPress\Feature\WooCommerce
@felipeelia Done.

2023-02-01 12:43 UTC, JakePT commented on includes/classes/Feature/WooCommerce/Orders.php
> +		if ( 'shop_order' !== $_GET['post_type'] ) { // phpcs:ignore WordPress.Security.NonceVerification.Recommended
@felipeelia Good catch. Fixed.

2023-02-01 12:44 UTC, JakePT commented on includes/classes/Feature/WooCommerce/Orders.php
> +		$response = Elasticsearch::factory()->remote_request(
@felipeelia Good catch. Fixed.

2023-02-02 21:33 UTC, merged