[WIP] Stop the Sync process if mapping failed
10up/ElasticPress pull request #3206
Opened 2022-12-14 07:54 UTC by burhandodhy

### Description of the Change

Closes #

### How to test the Change

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability

### Credits

Props @username, @username2, ...

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2022-12-16 13:32 UTC, felipeelia requested changes

2022-12-16 13:32 UTC, felipeelia commented on includes/classes/Command.php
>  						return false;
To make it more readable, can we split these functions into different lines?
```suggestion
						/* translators: Error message */
						WP_CLI::error(
							sprintf(
								esc_html__( 'Mapping failed: %s', 'elasticpress' ),
								$result->get_error_message()
							)
						);
```

2022-12-16 13:32 UTC, felipeelia commented on includes/classes/Elasticsearch.php
> +	 * @return boolean|WP_ERROR
The type here is actually `WP_Error`, isn't it?

2022-12-16 13:32 UTC, felipeelia commented on includes/classes/Elasticsearch.php
>  	public function put_mapping( $index, $mapping ) {
As I said in slack, we can't simply change the return and introduce a breaking change. Let's please add an optional third parameter where devs can choose between receiving `false` or the actual error.

2022-12-19 15:59 UTC, burhandodhy commented on includes/classes/Elasticsearch.php
>  	public function put_mapping( $index, $mapping ) {
@felipeelia  I made the changes as you requested. 

2023-01-04 17:46 UTC, felipeelia requested changes

2023-01-04 17:46 UTC, felipeelia commented on includes/classes/IndexHelper.php
> +				$message .= sprintf( esc_html__( '%sMapping has failed, which will cause ElasticPress search results to be incorrect. Please click `Delete all Data and Start a Fresh Sync` to retry mapping.', 'el
```suggestion
				$message  = sprintf( esc_html__( 'Mapping failed: %s', 'elasticpress' ), $error['message'] );
				$message .= "\n";
				$message .= esc_html__( 'Mapping has failed, which will cause ElasticPress search results to be incorrect. Please click `Delete all Data and Start a Fresh Sync` to retry mapping.', 'elasticpress' );
```

2023-01-04 19:19 UTC, merged