Cleanup Autosuggest description and change title for autosuggest and instant results
10up/ElasticPress pull request #3207
Opened 2022-12-14 13:15 UTC by burhandodhy

### Description of the Change

This PR updates the titles for the Autosuggest and Instant Results feature if the ElasticPress is connected with ep.io. Also it removed the old checks from the autosuggest description. 

<img width="787" alt="image" src="https://user-images.githubusercontent.com/7139602/207604928-141ea5ab-726c-4c80-b2a7-86995a263403.png">

Closes #3191 

### How to test the Change

### Changelog Entry

> Changed - Update title for Autosuggest and Instant results feature, if connected to ep.io

### Credits

Props @burhandodhy @felipeelia @NV607FOX 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests pass.

2022-12-16 13:43 UTC, felipeelia requested changes
@burhandodhy in addition to my comments below, there is also a visual problem we will need to address. This is how I'm seeing it in my local:

![image](https://user-images.githubusercontent.com/184628/208111375-590664a8-8d33-4b61-9bf7-cdcd21bdea91.png)

2022-12-16 13:43 UTC, felipeelia commented on includes/classes/Feature.php
> +
Open to discussion but can we remove the empty line between the method declaration and its content? I'm seeing this being added lately and it is not something used in WordPress in general.

2022-12-16 13:43 UTC, felipeelia commented on includes/classes/Feature/Autosuggest/Autosuggest.php
> +		/* translators: 1. Feature name;  */
The placeholder won't be replaced by the feature name but with the EP.io logo

2022-12-16 13:54 UTC, burhandodhy commented on includes/classes/Feature/Autosuggest/Autosuggest.php
> +		/* translators: 1. Feature name;  */
Thanks. Its fixed now.

2022-12-16 13:55 UTC, burhandodhy commented on includes/classes/Feature.php
> +
Makes sense. Done

2022-12-19 02:23 UTC, JakePT requested changes

2022-12-19 02:23 UTC, JakePT commented on includes/classes/Feature.php
> +		return sprintf( '<img class="feature-epio-logo" src="%s">', esc_url( plugins_url( '/images/logo-elasticpress-io.svg', EP_FILE ) ) );
@burhandodhy Can we add an `alt` attribute here.

2022-12-19 06:07 UTC, burhandodhy commented on includes/classes/Feature.php
> +		return sprintf( '<img class="feature-epio-logo" src="%s">', esc_url( plugins_url( '/images/logo-elasticpress-io.svg', EP_FILE ) ) );
@JakePT added. Can you please give another look?

2022-12-21 06:33 UTC, JakePT requested changes

2022-12-21 06:33 UTC, JakePT commented on includes/classes/Feature.php
> +		return sprintf( '<img class="feature-epio-logo" alt="elasticpress.io-logo" src="%s">', esc_url( plugins_url( '/images/logo-elasticpress-io.svg', EP_FILE ) ) );
So the alt text should be human readable, so the hyphen isn't necessary here. I would use `ElasticPresss.io logo`. Also, and I should have mentioned this before, ideally images have a width and height attribute. This ensures there's no shifting around during the page load. As far as I can tell this should be `width="110" height="20"`.

2022-12-21 09:14 UTC, JakePT approved these changes, later dismissed

2022-12-22 12:43 UTC, felipeelia requested changes
@burhandodhy some last changes before we merge it. Also, I don't know if it is something in my computer but the logo looks "pixelated" to me here (see below.) Even the full-size svg looks a bit pixelated to me.
![image](https://user-images.githubusercontent.com/184628/209136786-a2eb9bff-4689-4943-8271-0604f9e9e8f5.png)

2022-12-22 12:43 UTC, felipeelia commented on includes/classes/Feature/Autosuggest/Autosuggest.php
> +				);
This function call has an extra tab (it should be aligned with the variables.) Also, we should link it to the status report page now (the autosuggest section specifically.)

2022-12-22 12:43 UTC, felipeelia commented on includes/classes/Feature/Autosuggest/Autosuggest.php
> +
do you mind removing the extra line here as well @burhandodhy ?

2022-12-22 12:43 UTC, felipeelia commented on includes/classes/Feature/InstantResults/InstantResults.php
> +
do you mind removing the extra line here as well @burhandodhy ?

2023-01-03 13:57 UTC, burhandodhy commented on includes/classes/Feature/InstantResults/InstantResults.php
> +
Done

2023-01-03 13:58 UTC, burhandodhy commented on includes/classes/Feature/Autosuggest/Autosuggest.php
> +				);
Done

2023-01-03 13:58 UTC, burhandodhy commented on includes/classes/Feature/Autosuggest/Autosuggest.php
> +
Done

2023-01-04 13:43 UTC, felipeelia requested changes

2023-01-04 13:43 UTC, felipeelia commented on includes/classes/Feature/Autosuggest/Autosuggest.php
> +				'<a href="' . esc_url( admin_url( 'site-health.php?tab=debug' ) ) . '">',
@burhandodhy can you please change this link to point to the Status Report page? Thanks.

2023-01-04 14:46 UTC, merged