WP CLI instant results template commands
10up/ElasticPress pull request #3216
Opened 2022-12-20 01:18 UTC by oscarssanchez

### Description of the Change

This PR implements #3150

### How to test the Change

Test the three new commands:

```
wp elasticpress get-search-template <--- Should retrieve the search template in JSON
wp elasticpress put-search-template <--- Should send the search template
wp elasticpress delete-search-template <--- Should delete search template
```

### Changelog Entry

> Added - WP CLI commands  get-search-template put-search-template delete-search-template 
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability

### Credits

Props @oscarssanchez 

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2023-01-13 15:57 UTC, felipeelia requested changes
@oscarssanchez In addition to the points I've commented on, can we please standardize the commands' descriptions (some have Instant Results in lowercase, some don't mention it, etc.)? Thanks!

2023-01-13 15:57 UTC, felipeelia commented on includes/classes/Command.php
> +	 */
@oscarssanchez The "Options" section needs to come before the `@params`. Run `wp help elasticpress get-search-template` and you will see that the --pretty option is not recognized by the docs. Can we also add a `@since 4.5.0` here please?

2023-01-13 15:57 UTC, felipeelia commented on includes/classes/Command.php
> +		WP_CLI::success( esc_html__( 'Done', 'elasticpress' ) );
These output commands shouldn't have a "Done" in the end, so people can simply save its output in a JSON file without breaking it. Can we remove it please?

2023-01-13 15:57 UTC, felipeelia commented on includes/classes/Command.php
> +		WP_CLI::success( esc_html__( 'Done', 'elasticpress' ) );
Can we make this `Done.`, so it lines up with the other "done" we have in the plugin?

2023-01-13 15:57 UTC, felipeelia commented on includes/classes/Command.php
> +		WP_CLI::success( esc_html__( 'Done', 'elasticpress' ) );
Can we make this `Done.`, so it lines up with the other "done" we have in the plugin?

2023-01-17 14:51 UTC, oscarssanchez commented on includes/classes/Command.php
> +		WP_CLI::success( esc_html__( 'Done', 'elasticpress' ) );
Sure @felipeelia I have addressed here https://github.com/10up/ElasticPress/pull/3216/commits/3334bc24a0a748624bce21f427a2a92f5831fe06

2023-01-17 14:51 UTC, oscarssanchez commented on includes/classes/Command.php
> +		WP_CLI::success( esc_html__( 'Done', 'elasticpress' ) );
Addressed here https://github.com/10up/ElasticPress/pull/3216/commits/3334bc24a0a748624bce21f427a2a92f5831fe06 @felipeelia

2023-01-17 14:52 UTC, oscarssanchez commented on includes/classes/Command.php
> +		WP_CLI::success( esc_html__( 'Done', 'elasticpress' ) );
Makes sense to me. Addressed here https://github.com/10up/ElasticPress/pull/3216/commits/89710cf6b3d464facae72d0260e7fe9135014d15 @felipeelia

2023-01-17 14:52 UTC, oscarssanchez commented on includes/classes/Command.php
> +	 */
Addressed here @felipeelia https://github.com/10up/ElasticPress/pull/3216/commits/eaf4a0c52e1c1e03f706a10c7887e7bbd345a3a2

2023-01-20 13:23 UTC, merged