Fix: Prevent using the ES for coupon search queries
10up/ElasticPress pull request #3222
Opened 2022-12-20 14:29 UTC by burhandodhy

### Description of the Change

This PR fixes the issue where the search queries for coupon always go through the ES

Closes #3221

### How to test the Change

### Changelog Entry

> Fixed - Prevent search queries for coupon to use Elasticsearch

### Credits

Props @burhandodhy 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests pass.

2023-01-04 14:23 UTC, felipeelia requested changes

2023-01-04 14:23 UTC, felipeelia commented on includes/classes/Feature/WooCommerce/WooCommerce.php
> +
Can we remove this empty line, please?

2023-01-04 14:23 UTC, felipeelia commented on includes/classes/Feature/WooCommerce/WooCommerce.php
> +		if ( method_exists( $query, 'get' ) && 'shop_coupon' === $query->get( 'post_type' ) && empty( $query->query_vars['ep_integrate'] ) ) {
As we are using ep_integrate_search_queries now and that runs inside integrate_search_queries:
1. We can be sure $query is a WP_Query object and that class has the get method since WP 1.5. We don't need to check if that exists.
2. integrate_search_queries already deals with ep_integrate, and we shouldn't test it here again.

2023-01-11 12:17 UTC, burhandodhy commented on includes/classes/Feature/WooCommerce/WooCommerce.php
> +		if ( method_exists( $query, 'get' ) && 'shop_coupon' === $query->get( 'post_type' ) && empty( $query->query_vars['ep_integrate'] ) ) {
The check for the WP_Query is removed. However, the `ep_integrate` check is needed to handle the case where user explicitly set the `ep_integrate` to false in query. 

```
$query = new \WP_Query(
			[
				'post_type'    => 'shop_coupon',
				's'            => 'test-coupon',
				'ep_integrate' => false,
			]
		)
```

2023-01-20 14:24 UTC, merged