Add a download report button
10up/ElasticPress pull request #3319
Opened 2023-02-14 20:30 UTC by felipeelia

### Description of the Change

Closes #3288

### How to test the Change
1. Go to the Status Report page
2. Click on the Download report button

### Changelog Entry

> Added - New "Download report" button in the Status Report page

### Credits

Props @felipeelia 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests pass.

2023-02-15 10:08 UTC, JakePT requested changes

2023-02-15 10:08 UTC, JakePT commented on assets/css/status-report.css
> +		margin-left: 0.5rem;
I think rather than this, it would be better to change `.ep-copy-button-wrapper` so that it's no longer `flex`. This way the buttons inside will display properly as inline and there'll be a natural space between them.

2023-02-15 12:26 UTC, felipeelia commented on assets/css/status-report.css
> +		margin-left: 0.5rem;
That works @JakePT but then the spaces aren't even between spaces and the "Copied!" text:

![image](https://user-images.githubusercontent.com/184628/219026758-7f24d462-7ac5-4513-b200-44ed4011b3e8.png)

If we remove the space between the button and the text, it seems things will be too close in general:

![image](https://user-images.githubusercontent.com/184628/219027065-cc812b66-dd93-4eb7-8401-86d6c7b482da.png)

What would you prefer?

2023-02-17 02:28 UTC, JakePT commented on assets/css/status-report.css
> +		margin-left: 0.5rem;
@felipeelia Honestly, in playing with it I think I prefer the version in your first screenshot. That's just my preference though, I won't hold this up for it.

2023-02-17 02:28 UTC, JakePT submitted a review, later dismissed

2023-02-21 15:32 UTC, anjulahettige commented on assets/css/status-report.css
> +		margin-left: 0.5rem;
This was the approved version:
![image](https://user-images.githubusercontent.com/36264388/220388549-1d86657a-9636-4bfd-87e2-a67b7c8b153f.png)

2023-02-21 17:44 UTC, felipeelia commented on assets/css/status-report.css
> +		margin-left: 0.5rem;
Changed in 5680a98

2023-02-22 03:44 UTC, JakePT approved these changes

2023-02-22 13:23 UTC, merged