Fix: All public methods in Command class are treated as a wpcli command
10up/ElasticPress pull request #3320
Opened 2023-02-16 11:34 UTC by burhandodhy

### Description of the Change

Closes #

### How to test the Change

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability

### Credits

Props @username, @username2, ...

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2023-02-20 18:17 UTC, felipeelia requested changes
@burhandodhy asked for some changes on this one. Although I'm not a fan of introducing a whole new class to fix the original problem, I also see it being valid to separate concerns... 🤔

2023-02-20 18:17 UTC, felipeelia commented on includes/classes/Command.php
> +use ElasticPress\Command\Utility as Utility;
@burhandodhy you don't need to repeat the class name if you are keeping the same. The two lines above the new one have that same problem. `use ElasticPress\Command\Utility` is already enough.

2023-02-20 18:17 UTC, felipeelia commented on includes/classes/Command.php
> +		_doing_it_wrong( __METHOD__, esc_html__( 'This method is deprecated and will be removed from 5.0. Use \ElasticPress\Command\Utility::delete_transient_on_int instead.', 'elasticpress' ), '4.5.1' );
Instead of `_doing_it_wrong` we should call `_deprecated_function` in all these functions. Also, do you mind reviewing the last parameter of the function? You have it as `'4.5.1'` but that should be 4.5.0.

2023-02-20 18:17 UTC, felipeelia commented on includes/classes/Command/Utility.php
> + * @since 4.4.0
This should be 4.5.0

2023-02-20 18:17 UTC, felipeelia commented on includes/classes/Command/Utility.php
> +	 * @since 4.2.0
Although these methods exist before, the `@since` tag should be either removed or updated to 4.5.0, as these are not the (exact) same methods. Let's remove them for now, as all of them are `4.5.0`

2023-02-21 04:51 UTC, burhandodhy commented on includes/classes/Command.php
> +use ElasticPress\Command\Utility as Utility;
I followed the same convention. However, I removed the alias from all the classes.

2023-02-21 04:51 UTC, burhandodhy commented on includes/classes/Command.php
> +		_doing_it_wrong( __METHOD__, esc_html__( 'This method is deprecated and will be removed from 5.0. Use \ElasticPress\Command\Utility::delete_transient_on_int instead.', 'elasticpress' ), '4.5.1' );
Its done.

2023-02-22 18:02 UTC, felipeelia requested changes
In addition to the small change that still needs to be done here @burhandodhy, do you mind fixing the git conflict that arose? Thanks.

2023-02-22 18:02 UTC, felipeelia commented on tests/php/TestCommands.php
> +use ElasticPress\Command\Utility as Utility;
@burhandodhy we don't need the alias here as well

2023-02-24 11:22 UTC, burhandodhy commented on tests/php/TestCommands.php
> +use ElasticPress\Command\Utility as Utility;
Done

2023-02-24 12:49 UTC, felipeelia requested changes
@burhandodhy the conflict was not properly fixed (the new code was reverted.) So I took a deeper look into the code and it seems we still have some inconsistencies and breaking changes. Do you mind giving it another thorough review? Are you 100% sure this does not break any existing behavior including hooks? Thanks.

2023-02-24 12:49 UTC, felipeelia commented on includes/classes/Command.php
> +		$setup_option = isset( $assoc_args['setup'] ) ? $assoc_args['setup'] : false;
@burhandodhy this actually should keep the change introduced in #3301

2023-02-24 12:49 UTC, felipeelia commented on includes/classes/Command.php
> +		remove_action( 'ep_index_batch_new_attempt', [ Utility::class, 'maybe_interrupt_sync' ] );
Are you sure about these two method names? Shouldn't they be `call_ep_cli_put_mapping` and `should_interrupt_sync`?

2023-02-24 12:49 UTC, felipeelia commented on includes/classes/Command.php
> +
It seems a new line was introduced here by accident. Do you mind removing it?

2023-02-24 12:49 UTC, felipeelia commented on includes/classes/Command.php
> +				Utility::delete_transient();
Making this change we are no longer calling the `ep_cli_before_clear_index` and `ep_cli_after_clear_index` actions. Is there a reason why?

2023-02-27 13:34 UTC, felipeelia requested changes
@burhandodhy we are almost there. There is a change that didn't seem to be pushed and also I just remembered we need to change the --remove parameter [here](https://github.com/10up/ElasticPress/blob/develop/.github/workflows/build-docs.yml#L49).

2023-02-27 13:34 UTC, felipeelia commented on tests/php/TestCommands.php
> +use ElasticPress\Command\Utility as Utility;
It seems this wasn't changed @burhandodhy ?

2023-02-27 20:31 UTC, merged