ngram fields for orders autosuggest + refactor
10up/ElasticPress pull request #3324
Opened 2023-02-20 14:18 UTC by felipeelia

TBD 

### Description of the Change

Closes #3281 

### How to test the Change

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability

### Credits

Props @username, @username2, ...

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2023-02-21 01:47 UTC, JakePT requested changes

2023-02-21 01:47 UTC, JakePT commented on includes/classes/Feature/WooCommerce/Orders.php
> +			'_order_key',
`_order_key` is the hidden value used in the URL for access to the order status page, and isn't publicly exposed, so it's not the field we'll want to search. The order number is saved as _order_number, but we don't seem to be indexing that in the current version.

2023-02-21 01:47 UTC, JakePT commented on includes/classes/Feature/WooCommerce/Orders.php
> +			'_shipping_last_name',
We're not currently displaying the shipping names, so do we need to use them for this?

2023-02-21 15:10 UTC, anjulahettige commented
For now, we are just searching on the fields that are being displayed.

2023-02-21 17:35 UTC, felipeelia commented on includes/classes/Feature/WooCommerce/Orders.php
> +			'_order_key',
I've added some code in d890c3c to use that instead @JakePT. Do you mind checking it again?

2023-02-21 17:35 UTC, felipeelia commented on includes/classes/Feature/WooCommerce/Orders.php
> +			'_shipping_last_name',
Changed in d890c3c as well.

2023-02-23 03:40 UTC, JakePT approved these changes

2023-02-23 11:54 UTC, merged