WIP: Refine ElasticPress blocks.
10up/ElasticPress pull request #3403
Opened 2023-03-23 22:09 UTC by JakePT

### Description of the Change
Introduces the following features, improvements, and refinements to our blocks:

- All blocks have been moved into an "ElasticPress" block category and the "(ElasticPress)" identifier has been removed from their names.
- Descriptions and keywords have been added to all blocks.
- All blocks now support the following features in themes that support them:
  - Color
    - Background
    - Link
    - Text
  - Position
    - Sticky
  - Spacing
    - Margin
    - Padding
  - Typography
    - Font size
    - Line height
 - The Facet blocks have been renamed from "Facet by..." to "Filter by...".
 - References to filtering by "Meta" have been replaced with "Metadata" for consistency with how [WordPress documentation](https://developer.wordpress.org/plugins/metadata/) and #3068 refer to it.
- The _Filter by Taxonomy_ and _Filter by Metadata_ blocks now share a single edit component to avoid code reuse.
- Any functionality shared by the _Filter by Metadata Range_ and the other _Filter by_ blocks has been abstracted into shared components.
- Custom block previews have been replaced with implementations of [`ServerSideRender`](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-server-side-render/).
- REST API requests in edit components have been replaced with implementations of [`useSelect`](https://make.wordpress.org/core/2019/06/10/introducing-usedispatch-and-useselect/) and a custom [data store](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-data/#registering-a-store). This eliminates repeated API requests for data that has already been retrieved, including filterable taxonomies, meta fields, and meta range previews.
- When adding _Filter by Taxonomy_ or _Filter by Metadata_ blocks, users are now prompted to select a taxonomy or meta field before a preview is shown. This is consistent with several core blocks and the existing functionality of the _Facet by Meta Range_ block.
- The labels for the block inspector panels containing controls for block attributes have all been changed to just "Settings" for consistency with core blocks that only have a single panel.

Closes #3384

### How to test the Change

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability

### Credits

Props @JakePT 

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2023-06-07 22:52 UTC, JakePT commented on includes/classes/Indexable.php
> +			throw new \Exception( 'Meta fields not available.', 0 );
@felipeelia This error wasn't being caught in the API endpoint because the API endpoint expected a thrown exception. As far as I'm aware exceptions should be thrown rather than returned, but let me know if there's a better fix.

2023-06-07 23:14 UTC, JakePT commented
@felipeelia This includes renaming the facet blocks to "Filter by". Should we be renaming the Facets feature also?

2023-06-27 12:44 UTC, JakePT commented
@oscarssanchez While working on these changes the Facet by Post Type block was introduced. To make that new block consistent with the changes made to the existing blocks, the following will need to be done:

- Rename the block to "Filter by Post Type"
- Add a description "Let visitors filter your content by post type."
- Use the elasticpress block category.
- Add keywords and textdomain to block.json.
- Add support for the same features, namely color, position, spacing and typography.
- Use the same filter icon.
- Use the share components for the order controls and display count control.
- Display a placeholder when first inserting the block.
- Create a post type control for selecting post type, based on the FacetMetaControl and FacetTaxonomyControl introduced in this PR.
- To support the post type control you'll need to add actions to the store to retrieve post types.

2023-07-25 18:01 UTC, oscarssanchez commented
@JakePT I've applied the changes here https://github.com/10up/ElasticPress/pull/3553 can you review please?

2023-08-03 17:31 UTC, felipeelia requested changes
Overall it looks good @JakePT but we'll need to address a few things before merging it (especially the methods removal instead of deprecation)

2023-08-03 17:31 UTC, felipeelia commented on assets/js/blocks/facets/common/components/empty-response-placeholder.js
> +				  )}
Shouldn't this be coming from the facet/filter? It seems weird to have a switch here depending on the meta (if we have a 4th one coming in the future)

2023-08-03 17:31 UTC, felipeelia commented on assets/js/blocks/facets/common/components/facet-order-control.js
> +			label: __('A → Z', 'elasticpress'),
This should be a _x() with the comment as the context, no?

2023-08-03 17:31 UTC, felipeelia commented on includes/classes/Feature/Facets/Types/Meta/Block.php
We can't remove methods in a minor version, so instead of removing them completely, let's keep them as a wrapper for a _doing_it_wrong() or _deprecated_function() call (4.7.0 has a bunch of these that can be used as an example)

2023-08-03 17:31 UTC, felipeelia commented on includes/classes/Feature/Facets/Types/MetaRange/Block.php
> -
$attributes is actually passed to the filter below, so can't be removed.

2023-08-03 21:01 UTC, JakePT commented on assets/js/blocks/facets/common/components/empty-response-placeholder.js
> +				  )}
@felipeelia So in this case we’re sharing a lot of code between several facet blocks, so there isn’t anywhere to pass it down from. See: [https://github.com/10up/ElasticPress/pull/3403/files/db14e679a9d3718013a9bae9405f60cfdc279fde#diff-e1ffb7036f5d0252e614[…]85cde47d00d7fb1e7df417dR19](https://github.com/10up/ElasticPress/pull/3403/files/db14e679a9d3718013a9bae9405f60cfdc279fde#diff-e1ffb7036f5d0252e6140926216e93a9bf346215a85cde47d00d7fb1e7df417dR19) We share the edit component for the checkbox filters, so we would need to create a couple more files with a bunch of boilerplate just to pass down a different string.

2023-08-03 21:31 UTC, JakePT commented on includes/classes/Feature/Facets/Types/MetaRange/Block.php
> -
@felipeelia `$attributes` is passed as the first parameter of the `render_block` function, so it will be passed to the filter. We just don't pass it through `parse_attributes` anymore,

2023-08-03 21:31 UTC, JakePT commented on includes/classes/Feature/Facets/Types/Meta/Block.php
@felipeelia I've restored these methods and deprecated them.

2023-08-03 21:32 UTC, JakePT commented on assets/js/blocks/facets/common/components/facet-order-control.js
> +			label: __('A → Z', 'elasticpress'),
@felipeelia I think I just copied this from core, since I don't usually leave a `translators` unless there's a placeholder, but I've updated it to use `_x` instead.

2023-08-03 21:58 UTC, felipeelia requested changes
a few more things @JakePT (i could be missing a few things, sorry in advance)

2023-08-03 21:58 UTC, felipeelia commented on includes/classes/Feature/Facets/Facets.php
> -	public function admin_scripts( $hook ) {
@JakePT this should not be removed but wrap a _doing_it_wrong() call.

2023-08-03 21:58 UTC, felipeelia commented on includes/classes/Feature/Facets/Types/Meta/Block.php
> +			esc_html__( 'Since the Meta facets is only available as a block, attribute parsing is now left to block.json.', 'elasticpress' ),
I'm assuming this mechanic is compatible with WordPress 5.6, right?

2023-08-03 21:58 UTC, felipeelia commented on includes/classes/Feature/Facets/Types/MetaRange/Block.php
> -
my bad, thanks!

2023-08-03 21:58 UTC, felipeelia commented on includes/classes/Feature/Facets/Types/MetaRange/Block.php
> -	protected function parse_attributes( $attributes ) {
this should be a wrapper for a _doing_it_wrong() call

2023-08-03 21:58 UTC, felipeelia commented on includes/classes/Feature/Facets/Types/Taxonomy/Block.php
> -	public function render_block_preview( $request ) {
this one too

2023-08-03 21:58 UTC, felipeelia commented on includes/classes/Feature/Facets/Types/Taxonomy/Block.php
> -	protected function parse_attributes( $attributes ) {
same here

2023-08-08 18:19 UTC, merged