Integrate search suggestion
10up/ElasticPress pull request #3425
Opened 2023-04-03 15:54 UTC by burhandodhy

### Description of the Change

Closes #

### How to test the Change

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability

### Credits

Props @username, @username2, ...

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2023-05-25 17:24 UTC, felipeelia reviewed
@burhandodhy identified some changes we'll need to do but happy to talk about it next week.

2023-05-25 17:24 UTC, felipeelia commented on elasticpress.php
> +	);
Let's ask @brandwaffle where in the list he wants to add this new feature. It could be one of the most visible ones instead of the last in the list.

2023-05-25 17:24 UTC, felipeelia commented on includes/classes/Feature/DidYouMean/DidYouMean.php
> + * @since   4.6
Let's make it 4.6.0 (with the final .0) everywhere, please :)

2023-05-25 17:24 UTC, felipeelia commented on includes/classes/Feature/DidYouMean/DidYouMean.php
> +			'force_inactive'  => true,
Do we need this to be true?

2023-05-25 17:24 UTC, felipeelia commented on includes/classes/Feature/DidYouMean/DidYouMean.php
> +		add_filter( 'ep_post_mapping', [ $this, 'add_mapping' ], 10 );
```suggestion
		add_filter( 'ep_post_mapping', [ $this, 'add_mapping' ] );
```

2023-05-25 17:24 UTC, felipeelia commented on includes/classes/Feature/DidYouMean/DidYouMean.php
> +		$mapping['mappings']['properties']['post_content']['fields'] = [
Depending on the ES version this might need to be different (with a `'post'` between properties and post_content), no?

2023-05-25 17:24 UTC, felipeelia commented on includes/classes/Feature/DidYouMean/DidYouMean.php
> +		return apply_filters( 'ep_did_you_mean_suggestion_html', $html, $query );
Let's pass the term(s) here as well.

2023-05-25 17:24 UTC, felipeelia commented on includes/classes/Feature/DidYouMean/DidYouMean.php
> +		 * @param {array} $wp_query WP_Query object
If $wp_query is a WP_Query object, the type of this `@param` needs to reflect that.

2023-05-25 17:24 UTC, felipeelia commented on includes/classes/Feature/DidYouMean/DidYouMean.php
> +	 * @param WP_Query $query WP_Query object
It needs to document the return as well (and as it can return `false` it can be signed as `: string`

2023-05-25 17:24 UTC, felipeelia commented on includes/classes/Feature/DidYouMean/DidYouMean.php
> +			$query->set( 'ep_suggestion', true );
I think we will need different names here, no? One flag to say the query should search for suggestions and a different one to actually store suggestions?

2023-05-25 17:24 UTC, felipeelia commented on includes/classes/Indexable/Post/QueryIntegration.php
> +			$query->ep_suggestion         = isset( $ep_query['suggest']['ep_suggestion'] ) && isset( $ep_query['suggest']['ep_suggestion'][0] ) ? $ep_query['suggest']['ep_suggestion'][0] : [];
What about multiple suggestions?

2023-05-26 05:59 UTC, burhandodhy commented on includes/classes/Feature/DidYouMean/DidYouMean.php
> +			'force_inactive'  => true,
It depends; if we don't set it to true, the feature will be automatically enabled upon enabling the search feature.

2023-05-29 06:26 UTC, burhandodhy commented on includes/classes/Feature/DidYouMean/DidYouMean.php
> +			'force_inactive'  => true,
Found the root cause of the problem, and I removed my changes. 

2023-05-29 06:26 UTC, burhandodhy commented on includes/classes/Feature/DidYouMean/DidYouMean.php
> +		$mapping['mappings']['properties']['post_content']['fields'] = [
Done.

2023-05-29 06:50 UTC, burhandodhy commented on includes/classes/Indexable/Post/QueryIntegration.php
> +			$query->ep_suggestion         = isset( $ep_query['suggest']['ep_suggestion'] ) && isset( $ep_query['suggest']['ep_suggestion'][0] ) ? $ep_query['suggest']['ep_suggestion'][0] : [];
The 0 index does have all the suggestions.

2023-06-02 18:13 UTC, felipeelia requested changes
@burhandodhy Can we also please add some documentation about how people can use this feature?

2023-06-02 18:13 UTC, felipeelia commented on includes/classes/Feature/DidYouMean/DidYouMean.php
> +		 * @hook ep_search_suggestion_analyzer
Can we add a `@since` here @burhandodhy ?

2023-06-02 18:13 UTC, felipeelia commented on includes/classes/Feature/DidYouMean/DidYouMean.php
> +		$search_analyzer = apply_filters( 'ep_search_suggestion_analyzer', $search_analyzer, $formatted_args, $args, $wp_query );
Can we add a simple unit test for this filter?

2023-06-06 05:39 UTC, burhandodhy commented on includes/classes/Feature/DidYouMean/DidYouMean.php
> +			$query->set( 'ep_suggestion', true );
Done. From now `suggested_terms` would have all the suggestions.

2023-06-07 13:41 UTC, felipeelia requested changes
@burhandodhy some final changes we'll need to make before this can be merged. We also need to add somewhere that code is required to display the suggestions. Thoughts?

2023-06-07 13:41 UTC, felipeelia commented on includes/classes/Feature/DidYouMean/DidYouMean.php
> +	 * @return string
It can also return void @burhandodhy

2023-06-07 13:41 UTC, felipeelia commented on includes/classes/Feature/DidYouMean/DidYouMean.php
> +		echo $html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
Why can't we sanitize it with wp_kses_post or similar?

2023-06-07 13:41 UTC, felipeelia commented on includes/classes/Feature/DidYouMean/DidYouMean.php
> +				<label><input name="settings[search_behavior]" type="radio" <?php checked( ! (bool) $settings['search_behavior'] ); ?> value="0"><?php esc_html_e( 'Display a top suggestion', 'elasticpress' ); ?>
```suggestion
				<label><input name="settings[search_behavior]" type="radio" <?php checked( ! (bool) $settings['search_behavior'] ); ?> value="0"><?php esc_html_e( 'Display the top suggestion', 'elasticpress' ); ?></label><br>
```

2023-06-07 13:41 UTC, felipeelia commented on includes/classes/Feature/DidYouMean/DidYouMean.php
> +		$html  = $this->get_original_search_term();
Any reason why sometimes we consider it possible to work with a custom WP_Query and on this function it only uses the main_query?

2023-06-07 13:41 UTC, felipeelia commented on includes/classes/Feature/DidYouMean/DidYouMean.php
> +		$this->summary = __( '"Did You Mean" search feature provides alternative suggestions for misspelled or ambiguous search queries, enhancing search accuracy and user experience.', 'elasticpress' );
```suggestion
		$this->summary = __( 'Recommend alternative search terms for misspelled queries or terms with no results', 'elasticpress' );
```

per https://github.com/10up/ElasticPress/issues/2089#issuecomment-1579014160

2023-06-07 13:56 UTC, felipeelia commented on includes/classes/Feature/DidYouMean/DidYouMean.php
> +		return parent::requirements_status();
I thought we've talked about it before but I might be wrong. This feature should NOT return a FeatureRequirementsStatus->code 0, it should behave exactly like Instant Results, with a code 1.

2023-06-07 14:42 UTC, burhandodhy commented on includes/classes/Feature/DidYouMean/DidYouMean.php
> +		$html  = $this->get_original_search_term();
Yes, the logic behind this is to display the original search term only for the main search query.

2023-06-07 15:54 UTC, burhandodhy commented on includes/classes/Feature/DidYouMean/DidYouMean.php
> +		return parent::requirements_status();
Done

2023-06-07 15:55 UTC, burhandodhy commented on includes/classes/Feature/DidYouMean/DidYouMean.php
> +		$this->summary = __( '"Did You Mean" search feature provides alternative suggestions for misspelled or ambiguous search queries, enhancing search accuracy and user experience.', 'elasticpress' );
I missed that comment. updated the summary.

2023-06-07 15:55 UTC, burhandodhy commented on includes/classes/Feature/DidYouMean/DidYouMean.php
> +		echo $html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
Good catch. Done

2023-06-07 15:55 UTC, burhandodhy commented on includes/classes/Feature/DidYouMean/DidYouMean.php
> +	 * @return string
Done

2023-06-07 19:43 UTC, merged