WooCommerce weight by date
10up/ElasticPress pull request #3462
Opened 2023-05-16 13:27 UTC by MARQAS

### Description of the Change
This PR will add two options to control the weighting in the search results for products. One will disable the weighting only for the product queries and the other will disable the weighting on any query that includes products.

Closes #3177 

### How to test the Change

- Enable the WooCommerce feature
- Notice that the Weight results by date settings will now have two additional options in it
- Select the third option (Disable for products) and search for a product on the products page(admin) and note that it will not have weighting. Normal search will have weighting even if it contains products in it. 
- Select the 4th option(Disable Weighting in any query that includes products) and search for a product and note that it will not have weighting. Any query that has a post-type product in it will not have the weighting args.
-  Selecting the 2nd option will disable it for any search you make.

### Changelog Entry

> Added - Two new options for Weight results by date to manage weighting for product post-types

### Credits

Props @MARQAS @felipeelia 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests pass.

2023-05-19 17:44 UTC, felipeelia requested changes
We'll need to separate concerns a bit better here before we can merge it @MARQAS. Perhaps a filter in Search that is used by WooCommerce is all you really need. I'm also not sure how this change interferes with regular weighting.

2023-05-19 17:44 UTC, felipeelia commented on includes/classes/Feature/Search/Search.php
> +use ElasticPress\Features as Features;
@MARQAS you do not need an alias of a class if you are using the original name. `use ElasticPress\Features;` should be enough (you can fix all the others as well.)

2023-05-19 17:44 UTC, felipeelia commented on includes/classes/Feature/Search/Search.php
> +		return $decaying;
The Search class should not be aware of a "product" post type, that is something to be dealt with by the WooCommerce class.

2023-05-19 17:44 UTC, felipeelia commented on includes/classes/Feature/Search/Search.php
> +				 * @since  5.0.0
Let's please change this to `4.6.0`

2023-05-19 17:44 UTC, felipeelia commented on includes/classes/Feature/Search/Weighting.php
> +use ElasticPress\Feature as Feature;
Same as above

2023-05-19 17:44 UTC, felipeelia commented on includes/classes/Feature/Search/Weighting.php
> +					}
This class should not be dealing with specific post types as well.

2023-05-19 17:44 UTC, felipeelia commented on includes/classes/Feature/Search/Weighting.php
> +		$feature_settings = Utils\get_option( 'ep_feature_settings', [] );
Is this variable being used?

2023-05-19 17:44 UTC, felipeelia commented on includes/classes/Feature/Search/Weighting.php
> +		$search = $features->get_registered_feature( 'search' );
Not sure why the docblock with the var type here but we generally go with `Features::factory()->get_registered_feature( 'search' );`

2023-05-19 17:44 UTC, felipeelia commented on includes/classes/Feature/Search/Weighting.php
> +		}
Is there any reason why we would not apply date decaying AND regular weighting? I don't think one thing excludes the other.

2023-05-19 17:44 UTC, felipeelia commented on includes/classes/Feature/WooCommerce/WooCommerce.php
> +		add_action( 'ep_weight_settings_after_search', [ $this, 'add_weight_settings_search' ], 10, 1 );
```suggestion
		add_action( 'ep_weight_settings_after_search', [ $this, 'add_weight_settings_search' ] );
```

2023-05-19 17:44 UTC, felipeelia commented on includes/classes/Feature/WooCommerce/WooCommerce.php
> +	 * @since 5.0.0
Let's change the `@since` tag here as well.

2023-05-19 17:44 UTC, felipeelia commented on tests/php/features/TestSearch.php
> +	 * @since 5.0
Same here

2023-05-19 17:44 UTC, felipeelia commented on tests/php/features/TestSearch.php
> +			)
This is a very nice usage of isset()!

2023-05-19 17:44 UTC, felipeelia commented on tests/php/features/TestSearch.php
> +		);
Tests will need some improvement here @MARQAS. We need to be sure that `disabled_products` only interferes with queries that has only products, so we need to test it against queries that have products and something else. Same for disabled_products_all.

2023-05-30 13:39 UTC, felipeelia requested changes

2023-05-30 13:39 UTC, felipeelia commented on includes/classes/Feature/Search/Search.php
> +	public function is_decaying_enabled( $post_type = [] ) {
@MARQAS I think it makes more sense to pass all the args. People using the new filter could use more than the post type(s) to decide if the decay should or not be applied.

2023-05-30 13:39 UTC, felipeelia commented on includes/classes/Feature/Search/Weighting.php
> +					}
I guess I asked this before but what is the relationship between fields weighting and date decay @MARQAS ?

2023-05-30 13:39 UTC, felipeelia commented on includes/classes/Feature/WooCommerce/WooCommerce.php
> +		<label><input name="settings[decaying_enabled]" type="radio" <?php checked( $settings['decaying_enabled'], 'disabled_products_all' ); ?> value="disabled_products_all"><?php esc_html_e( 'Disable Wei
Let's make these values a bit more intuitive. What do you think about `disabled_only_products` and `disabled_includes_products`? Also, let's run those options by @brandwaffle.

2023-05-30 13:39 UTC, felipeelia commented on includes/classes/Feature/WooCommerce/WooCommerce.php
> +		if ( ( is_array( $post_type ) && in_array( 'product', $post_type, true ) && 'disabled_products_all' === $settings['decaying_enabled'] ) || ( 'product' === $post_type && in_array( $settings['decayin
Let's split this into more than one big statement. Also, remember to use early returns.

2023-05-30 13:39 UTC, felipeelia commented on tests/php/features/TestSearch.php
> +		);
Let's create some custom methods like `assertDecayEnabled` to abstract all this a bit. It is becoming hard to understand what exactly we want to make sure here.

2023-05-30 13:40 UTC, felipeelia commented on includes/classes/Feature/Search/Weighting.php
> +		}
This was not addressed but I made a new comment about it anyway.

2023-06-07 16:31 UTC, burhandodhy approved these changes
LGTM

2023-06-07 19:45 UTC, merged