Facet by post type
10up/ElasticPress pull request #3473
Opened 2023-05-26 22:02 UTC by oscarssanchez

### Description of the Change

Closes #

### How to test the Change

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability

### Credits

Props @username, @username2, ...

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2023-05-31 12:47 UTC, felipeelia requested changes
@oscarssanchez we will need to make some changes before merging this one. I was also expecting at least unit tests covering all the new filters. Do you think that would be possible? If not we can regroup and I can take this one over. We'll also need e2e tests for it.

2023-05-31 12:47 UTC, felipeelia commented on includes/classes/Feature/Facets/Types/PostType/Block.php
> +				/* translators: Meta field name */
This should say `Post type name`.

2023-05-31 12:47 UTC, felipeelia commented on includes/classes/Feature/Facets/Types/PostType/Block.php
> +				'searchPlaceholder' => esc_html_x( 'Search', 'Facet by meta search placeholder', 'elasticpress' ),
The second parameter here needs to be changed.

2023-05-31 12:47 UTC, felipeelia commented on includes/classes/Feature/Facets/Types/PostType/FacetType.php
> +		return apply_filters( 'ep_facet_post_type_filter_type', 'ep_post_type' );
Filter types don't need the `ep_` prefix.

2023-05-31 12:47 UTC, felipeelia commented on includes/classes/Feature/Facets/Types/PostType/FacetType.php
> +		 * @hook ep_facet_filter_type
The filter name here needs to be adjusted.

2023-05-31 12:47 UTC, felipeelia commented on includes/classes/Feature/Facets/Types/PostType/FacetType.php
> +	 * @since 4.6.0
As this is a new file, the methods don't need a `@since` tag.

2023-05-31 12:47 UTC, felipeelia commented on includes/classes/Feature/Facets/Types/PostType/FacetType.php
> +				'size'  => apply_filters( 'ep_facet_post_type_size', 10000, 'post_type' ),
This new filter needs docs and I'm not sure why we would need the extra `'post_type'` string there. Shouldn't we pass `$post_types` instead?

2023-05-31 12:47 UTC, felipeelia commented on includes/classes/Feature/Facets/Types/PostType/FacetType.php
> +	 * @since 4.6.0
We need to remove this `@since` tag from here as well.

2023-05-31 12:47 UTC, felipeelia commented on includes/classes/Feature/Facets/Types/PostType/FacetType.php
> +				$filters[0]['terms']['post_type.raw'][] = $post_type;
Won't this `$filters[0]` override the first filter set?

2023-05-31 12:47 UTC, felipeelia commented on includes/classes/Feature/Facets/Types/PostType/FacetType.php
> +		$indexable_post_types = \ElasticPress\Indexables::factory()->get( 'post' )->get_indexable_post_types();
I wonder if we shouldn't use searchable post types here instead. Thoughts?

2023-05-31 12:47 UTC, felipeelia commented on tests/php/features/TestFacetTypePostTypeRenderer.php
> +	 * @since 4.6.0
Let's transfer this `@since` to the file docblock

2023-06-01 16:19 UTC, oscarssanchez commented on includes/classes/Feature/Facets/Types/PostType/FacetType.php
> +				'size'  => apply_filters( 'ep_facet_post_type_size', 10000, 'post_type' ),
@felipeelia if we pass $post_types the aggregation will return aggregation for each post type (individually) instead of just the aggregation of post types.

This would create a scenario where you have facet by post type for each individual post type. An example: "facet by page", which wouldn't let us filter further since page is the last group where we can aggregate/group stuff.

2023-06-01 16:28 UTC, felipeelia commented on includes/classes/Feature/Facets/Types/PostType/FacetType.php
> +				'size'  => apply_filters( 'ep_facet_post_type_size', 10000, 'post_type' ),
`'size'  => apply_filters( 'ep_facet_post_type_size', 10000, $post_types ),` is what I meant @oscarssanchez. That would be just a way for developers to change the 10000 value depending on which post types are involved.

2023-06-02 13:28 UTC, oscarssanchez commented on includes/classes/Feature/Facets/Types/PostType/FacetType.php
> +				'size'  => apply_filters( 'ep_facet_post_type_size', 10000, 'post_type' ),
Now it makes sense to me thanks for clarification @felipeelia

2023-06-02 14:21 UTC, felipeelia commented on includes/classes/Feature/Facets/Types/PostType/Block.php
> +				/* translators: Meta field name */
Adjusted in ab449e1.

2023-06-02 14:21 UTC, felipeelia commented on includes/classes/Feature/Facets/Types/PostType/Block.php
> +				'searchPlaceholder' => esc_html_x( 'Search', 'Facet by meta search placeholder', 'elasticpress' ),
Adjusted in ab449e1.

2023-06-02 14:21 UTC, felipeelia commented on includes/classes/Feature/Facets/Types/PostType/FacetType.php
> +		return apply_filters( 'ep_facet_post_type_filter_type', 'ep_post_type' );
Keeping this one as the final array will use any allowed query string parameter, and that includes `'post_type'`, used by WP core.

2023-06-02 14:22 UTC, felipeelia commented on includes/classes/Feature/Facets/Types/PostType/FacetType.php
> +		 * @hook ep_facet_filter_type
Adjusted in ab449e1.

2023-06-02 14:22 UTC, felipeelia commented on includes/classes/Feature/Facets/Types/PostType/FacetType.php
> +	 * @since 4.6.0
Adjusted in ab449e1.

2023-06-02 14:22 UTC, felipeelia commented on includes/classes/Feature/Facets/Types/PostType/FacetType.php
> +				'size'  => apply_filters( 'ep_facet_post_type_size', 10000, 'post_type' ),
Changed in ab449e1.

2023-06-02 14:22 UTC, felipeelia commented on includes/classes/Feature/Facets/Types/PostType/FacetType.php
> +	 * @since 4.6.0
Adjusted in ab449e1.

2023-06-02 14:22 UTC, felipeelia commented on includes/classes/Feature/Facets/Types/PostType/FacetType.php
> +				$filters[0]['terms']['post_type.raw'][] = $post_type;
Changed in ab449e1.

2023-06-02 14:23 UTC, felipeelia commented on includes/classes/Feature/Facets/Types/PostType/FacetType.php
> +		$indexable_post_types = \ElasticPress\Indexables::factory()->get( 'post' )->get_indexable_post_types();
Using searchable post types instead, otherwise it'll list shop_coupons and others.

2023-06-02 14:23 UTC, felipeelia commented on tests/php/features/TestFacetTypePostTypeRenderer.php
> +	 * @since 4.6.0
Adjusted in ab449e1.

2023-06-05 08:19 UTC, burhandodhy commented on includes/classes/Feature/Facets/Types/PostType/Block.php
> +	 * Check permissions of the /facets/taxonomies REST endpoint.
Shouldn't it be `/facets/post-type REST endpoint"?

2023-06-05 08:44 UTC, burhandodhy commented on includes/classes/Feature/Facets/Types/PostType/Block.php
> +		$renderer_class = apply_filters( 'ep_facet_renderer_class', __NAMESPACE__ . '\Renderer', 'post-type', 'block', $attributes );
Either add the proper documentation or a reference to this filter https://github.com/10up/ElasticPress/blob/feature/facet-post-type-ir/includes/classes/Feature/Facets/Types/Taxonomy/Block.php#L161

```
/** This filter is documented in includes/classes/Feature/Facets/Types/Taxonomy/Block.php */
```

2023-06-05 08:44 UTC, burhandodhy commented on includes/classes/Feature/Facets/Types/PostType/Block.php
> +	 */
Return type is missing

2023-06-05 08:44 UTC, burhandodhy commented on includes/classes/Feature/Facets/Types/PostType/Renderer.php
> +		$label = apply_filters( 'ep_post_type_value_label', $label, $value );
The filter's name is vague. We can rename it to `ep_facet_post_type_value_label`

2023-06-05 08:44 UTC, burhandodhy commented on includes/classes/Feature/Facets/Types/PostType/Renderer.php
> +			'ep_post_type_value_accessible_label',
Same as above the we can update it to `ep_facet_post_type_value_accessible_label`

2023-06-05 08:44 UTC, burhandodhy commented on includes/classes/Feature/Facets/Types/PostType/Renderer.php
> +	 * @param array  $values  Multidimentional array of values. Each value should have (string) `name`, (int) `count`, and (bool) `is_selected`.
Typo : `Multidimensional`

2023-06-05 13:42 UTC, burhandodhy approved these changes

2023-06-05 13:42 UTC, burhandodhy commented on includes/classes/Feature/Facets/Types/PostType/Renderer.php
> +		* @since 4.6.0
nit: Indentation looks off

2023-06-05 13:42 UTC, burhandodhy approved these changes, later dismissed

2023-06-05 20:51 UTC, merged

2023-06-28 21:09 UTC, JiveDig commented
I see the changelog that this was added in 4.6.0, but i don't see the facet widget or understand how to test this. Is this only in Instant Results?

2023-06-29 03:30 UTC, JakePT commented
Hi @JiveDig, Facet by Post Type is only available as a Block when using the block editor. If you're using something like [Classic Widgets](https://wordpress.org/plugins/classic-widgets/) then it will not be available, as the feature has not been implemented as a Widget.