WIP: Add ep_facet_special_slug_taxonomies filter
10up/ElasticPress pull request #3506
Opened 2023-06-21 00:12 UTC by oscarssanchez

### Description of the Change

Closes #

### How to test the Change

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability

### Credits

Props @username, @username2, ...

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2023-07-17 14:28 UTC, felipeelia requested changes

2023-07-17 14:28 UTC, felipeelia commented on tests/php/features/TestFacetTypeTaxonomy.php
> +	 */
Can we add a `@since` tag here, please?

2023-07-17 14:28 UTC, felipeelia commented on includes/classes/Feature/Facets/Types/Taxonomy/FacetType.php
> +		 */
We don't need to repeat the full docblock here, it is enough to change this to
```suggestion
		/** This filter is documented below */
```
like WordPress core does (in WP they mention the same file name, which I think is a redundancy.)

2023-07-24 18:07 UTC, oscarssanchez commented on tests/php/features/TestFacetTypeTaxonomy.php
> +	 */
This is now added here: https://github.com/10up/ElasticPress/pull/3506/files#diff-d36fb3af9a833294f34cf95964cbdc054fb4d401805400564aa71bc8ce01db90R329

2023-07-24 18:07 UTC, oscarssanchez commented on includes/classes/Feature/Facets/Types/Taxonomy/FacetType.php
> +		 */
I've removed the docblock @felipeelia

2023-07-25 12:53 UTC, felipeelia requested changes
@oscarssanchez do you mind putting together a small test covering the new add_taxonomy_attributes method, please?

2023-07-25 12:53 UTC, felipeelia commented on includes/classes/Feature/Facets/Types/Taxonomy/FacetType.php
> +		 * @return {array} $selected_filters Selected filters
@oscarssanchez in this docblock, $selected_filters is actually a parameter (then we need to add the return)

2023-07-25 12:53 UTC, felipeelia commented on includes/classes/Feature/WooCommerce/WooCommerce.php
> +	 */
Can we add a `@since` here please, @oscarssanchez ?

2023-07-25 12:53 UTC, felipeelia commented on includes/classes/Feature/WooCommerce/WooCommerce.php
> +	public function add_taxonomy_attributes( $attribute_taxonomies ) {
```suggestion
	public function add_taxonomy_attributes( array $attribute_taxonomies ) : array {
```
Especially for methods we have more control on, we are trying to specify types, @oscarssanchez :)

2023-07-25 12:53 UTC, felipeelia commented on tests/php/features/TestFacetTypeTaxonomy.php
> +		$this->assertGreaterThanOrEqual( 1, did_filter( 'ep_facet_tax_special_slug_taxonomies' ) );
@oscarssanchez can you add an assertion to check if `testmyfilter` was really added to the final return?

2023-07-28 15:43 UTC, oscarssanchez commented
@felipeelia I've added the test here https://github.com/10up/ElasticPress/pull/3506/files#diff-a0c161d42d6543c88327f86bccbc9be735eacb277cf60c3a35848775b03c24a0R364

2023-07-28 15:43 UTC, oscarssanchez commented on includes/classes/Feature/Facets/Types/Taxonomy/FacetType.php
> +		 * @return {array} $selected_filters Selected filters
This is now fixed here https://github.com/10up/ElasticPress/pull/3506/files @felipeelia

2023-07-28 15:44 UTC, oscarssanchez commented on includes/classes/Feature/WooCommerce/WooCommerce.php
> +	 */
Added here https://github.com/10up/ElasticPress/pull/3506/files#diff-5d9d9db6657b73dc4a922c343a4c5a48dc38584aa8cae7123c90a415900e456aR656 @felipeelia

2023-07-28 15:44 UTC, oscarssanchez commented on includes/classes/Feature/WooCommerce/WooCommerce.php
> +	public function add_taxonomy_attributes( $attribute_taxonomies ) {
Changed here @felipeelia

2023-07-28 15:44 UTC, oscarssanchez commented on tests/php/features/TestFacetTypeTaxonomy.php
> +		$this->assertGreaterThanOrEqual( 1, did_filter( 'ep_facet_tax_special_slug_taxonomies' ) );
Added here @felipeelia  https://github.com/10up/ElasticPress/pull/3506/files#diff-d36fb3af9a833294f34cf95964cbdc054fb4d401805400564aa71bc8ce01db90R354

2023-07-28 17:40 UTC, merged