[WIP] Add Did you Mean in Instant Result
10up/ElasticPress pull request #3564
Opened 2023-07-28 05:28 UTC by burhandodhy

### Description of the Change

Closes #

### How to test the Change

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability

### Credits

Props @username, @username2, ...

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2023-07-31 17:55 UTC, JakePT requested changes

2023-07-31 17:55 UTC, JakePT commented on assets/js/instant-results/components/layout/results.js
> +import DidYouMean from '../results/didYouMean';
@burhandodhy For consistency with the filenames from this project, can we name this file `did-you-mean.js`?

2023-07-31 17:55 UTC, JakePT commented on includes/classes/Feature/InstantResults/InstantResults.php
> +				'searchBehavior' => $did_you_mean_settings['search_behavior'],
It's probably too late if that name was already used for the PHP version, but I think "search behaviour" should be something more like "suggestions behaviour" or "display additional/multiple suggestions".

2023-07-31 17:55 UTC, JakePT commented on includes/classes/Feature/InstantResults/InstantResults.php
> +				'isDidYouMean'   => $did_you_mean_settings['active'],
I'd use something like `showSuggestions` for this. `showX` is a fairly common pattern for variables/properties that control the visibility of something in WordPress' own components.

2023-07-31 17:55 UTC, JakePT commented on assets/js/instant-results/components/results/didYouMean.js
> +					{__('Did you Mean: ', 'elasticpress')}
Can we use `sprintf()` here with a placeholder, just in case a different format is more appropriate in other languages? eg. `Did you mean: <a>%s</a>`. Also, "mean" probably shouldn't be capitalised.

See here for an example of how to include a link in translatable text in React in WordPress: https://github.com/10up/ElasticPress/blob/db14e679a9d3718013a9bae9405f60cfdc279fde/assets/js/blocks/facets/common/components/facet-meta-control.js#L42-L48

2023-07-31 17:55 UTC, JakePT commented on assets/js/instant-results/components/results/didYouMean.js
> +				<div className="ep-spell-suggestion">
Most classes in Instant Results are prefixed with `ep-search`. Can we use `ep-search-suggestion` for this class?

2023-07-31 17:55 UTC, JakePT commented on assets/js/instant-results/components/results/didYouMean.js
> +			{searchBehavior === 'list' && totalResults === 0 && otherTerms.length > 0 && (
This also needs to check `isDidYouMean` (or whatever we call it).

2023-07-31 17:55 UTC, JakePT commented on assets/js/instant-results/components/results/didYouMean.js
> +					{__('Did you Mean: ', 'elasticpress')}
Also, can we put this in a `<p>` tag inside the `<div>`?

2023-07-31 17:55 UTC, JakePT commented on assets/js/instant-results/components/results/didYouMean.js
> +					<ul>
Can we put these inside the wrapper `<div>`, for easier styling?

2023-07-31 17:58 UTC, JakePT commented on assets/js/instant-results/components/results/didYouMean.js
> +	const { isDidYouMean, searchBehavior } = window.epInstantResults;
Can we check these inside layout/results.js, and then pass them into this component via props? It seems like that's how I've been managing state for the components referenced in the results layout.

2023-08-01 07:19 UTC, burhandodhy commented on includes/classes/Feature/InstantResults/InstantResults.php
> +				'searchBehavior' => $did_you_mean_settings['search_behavior'],
@JakePT nice suggestion, but for PHP, it's a bit late. We can't change the key.

2023-08-01 07:19 UTC, burhandodhy commented on assets/js/instant-results/components/layout/results.js
> +import DidYouMean from '../results/didYouMean';
Done

2023-08-01 07:19 UTC, burhandodhy commented on includes/classes/Feature/InstantResults/InstantResults.php
> +				'isDidYouMean'   => $did_you_mean_settings['active'],
Done

2023-08-01 07:21 UTC, burhandodhy commented on assets/js/instant-results/components/results/didYouMean.js
> +					{__('Did you Mean: ', 'elasticpress')}
I attempted to use sprintf, but encountered an issue where passing the callback function as an argument led to its immediate execution.

2023-08-01 07:21 UTC, burhandodhy commented on assets/js/instant-results/components/results/didYouMean.js
> +				<div className="ep-spell-suggestion">
Done

2023-08-01 13:47 UTC, JakePT commented on assets/js/instant-results/components/results/didYouMean.js
> +					<ul>
@burhandodhy Sorry, here I meant that these elements should go inside the `ep-search-suggestion` div above. So that all the suggestion stuff is inside that div.

2023-08-08 12:17 UTC, merged