Override ES highlighting in IR
10up/ElasticPress pull request #3575
Opened 2023-08-02 17:52 UTC by oscarssanchez

### Description of the Change

This PR overrides the result coming from ES highlight, as noted in https://github.com/10up/ElasticPress/issues/3497 there seems to be an issue with how the highlighter returns results in partial/no matches

We should probably remove when we drop support for ES5
 
Closes https://github.com/10up/ElasticPress/issues/3497

### How to test the Change

### Changelog Entry

> Fixed - Bug fix - Highlighting returning inaccurate post title when partial/no term match

### Credits

Props @JakePT , @tomi10up, @oscarssanchez, @felipeelia   ...

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2023-08-02 19:39 UTC, JakePT requested changes

2023-08-02 19:39 UTC, JakePT commented on assets/js/instant-results/components/layout/results.js
> +		const resultsText = hit._source.post_title.replace(regex, (word) => `<mark>${word}</mark>`);
@oscarssanchez We should use the tag selected for highlighting from settings here. It should be available as the `highlight` property of `args` here: https://github.com/10up/ElasticPress/blob/95eae3388364a648eb2b819a8bc0ae74c4c84763/assets/js/instant-results/components/layout/results.js#L22 We should also check if this is empty, as if it is empty it means the user has selected no highlighting.

2023-08-03 06:16 UTC, oscarssanchez commented on assets/js/instant-results/components/layout/results.js
> +		const resultsText = hit._source.post_title.replace(regex, (word) => `<mark>${word}</mark>`);
@JakePT The problem that I see with the proposed approach is that we do not have access to `searchTerm` in result.js as well as the highlighting options. I think we could pass these as a prop if you think that's the best move. 

Alternatively, we could probably iterate through the different search forms and get the search term that way, but we still wouldn't know about the selected highlighting.

2023-08-03 12:59 UTC, JakePT commented on assets/js/instant-results/components/layout/results.js
> +		const resultsText = hit._source.post_title.replace(regex, (word) => `<mark>${word}</mark>`);
@oscarssanchez I think pass it through as a prop.

2023-08-03 23:23 UTC, JakePT approved these changes, later dismissed

2023-08-04 14:19 UTC, merged