New Filter ep_highlight_number_of_fragments.
10up/ElasticPress pull request #3600
Opened 2023-08-14 18:18 UTC by dgnorrod

Add to ./includes/classes/Feature/Search/Search.php a new filter to set the maximum number of fragments to highlight.

### Description of the Change

Added a filter that allows the dev to set the max number of fragments to highlight. This is just a convenience filter that relieves us from having to modify the formatted args directly. This maintains the current default setting of zero fragments.

Closes #3579 

### How to test the Change

Add this to a function:

```
// set number of fragments to 10 for post_content and post_excerpt fields (zero is the default)
add_filter( 'ep_highlight_number_of_fragments', function( $number_of_fragments, $field ) {
    if ( in_array( $field, [ 'post_content', 'post_excerpt' ] ) ) {
        $number_of_fragments = 10;
    }
    return $number_of_fragments;
} );

```
Check the query body "highlight" section for the "number_of_fragments" setting.

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability

### Credits

Props @username, @username2, ...
Props @dgnorrod

### Checklist:

- [x ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2023-09-07 16:59 UTC, felipeelia requested changes
Do you mind adding the documentation for the first parameter as well? Thanks!

2023-09-07 16:59 UTC, felipeelia commented on includes/classes/Feature/Search/Search.php
> +				'number_of_fragments' => apply_filters( 'ep_highlight_number_of_fragments', 0, $field ),
```suggestion
				/**
				 * Filter the maximum number of fragments highlighted for a searched field.
				 *
				 * @since 5.0.0
				 * @hook ep_highlight_number_of_fragments
				 * @param {int}    $field Number of fragments
				 * @param {string} $field Search field being setup
				 * @return {int} New maximum number of fragments to highlight for the searched field
				 */
				'number_of_fragments' => apply_filters( 'ep_highlight_number_of_fragments', 0, $field ),
```

2023-09-07 17:24 UTC, dgnorrod commented
Wow, what a stupid oversight. I can but not until the 18th. If you can wait that long, I’ll take care of it.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Felipe Elia ***@***.***>
Sent: Thursday, September 7, 2023 1:59:37 PM
To: 10up/ElasticPress ***@***.***>
Cc: Norrod, Dennis G. - US ***@***.***>; Author ***@***.***>
Subject: Re: [10up/ElasticPress] New Filter ep_highlight_number_of_fragments. (PR #3600)


EXTERNAL EMAIL - This email originated from outside of CACI. Do not click any links or attachments unless you recognize and trust the sender.





@felipeelia requested changes on this pull request.

Do you mind adding the documentation for the first parameter as well? Thanks!

________________________________

In includes/classes/Feature/Search/Search.php<https://github.com/10up/ElasticPress/pull/3600#discussion_r1318893229>:

> +                             /**
+                                * Filter the maximum number of fragments highlighted for a searched field.
+                                *
+                                * @since 5.0.0
+                                * @hook ep_highlight_number_of_fragments
+                                * @param  {string} $field Search field being setup.
+                                * @return  {int} New maximum number of fragments to highlight for the searched field.
+                                */
+                               'number_of_fragments' => apply_filters( 'ep_highlight_number_of_fragments', 0, $field ),


⬇️ Suggested change

-                               /**
-                                * Filter the maximum number of fragments highlighted for a searched field.
-                                *
-                                * @since 5.0.0
-                                * @hook ep_highlight_number_of_fragments
-                                * @param  {string} $field Search field being setup.
-                                * @return  {int} New maximum number of fragments to highlight for the searched field.
-                                */
-                               'number_of_fragments' => apply_filters( 'ep_highlight_number_of_fragments', 0, $field ),
+                               /**
+                                * Filter the maximum number of fragments highlighted for a searched field.
+                                *
+                                * @since 5.0.0
+                                * @hook ep_highlight_number_of_fragments
+                                * @param {int}    $field Number of fragments
+                                * @param {string} $field Search field being setup
+                                * @return {int} New maximum number of fragments to highlight for the searched field
+                                */
+                               'number_of_fragments' => apply_filters( 'ep_highlight_number_of_fragments', 0, $field ),


—
Reply to this email directly, view it on GitHub<https://github.com/10up/ElasticPress/pull/3600#pullrequestreview-1615883006>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BBLGSD2OCHEMFZYVJGNJ2F3XZH4PTANCNFSM6AAAAAA3QBTNGU>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

________________________________

This electronic message contains information from CACI International Inc or subsidiary companies, which may be company sensitive, proprietary, privileged or otherwise protected from disclosure. The information is intended to be used solely by the recipient(s) named above. If you are not an intended recipient, be aware that any review, disclosure, copying, distribution or use of this transmission or its contents is prohibited. If you have received this transmission in error, please notify the sender immediately.

2023-09-18 14:23 UTC, dgnorrod commented on includes/classes/Feature/Search/Search.php
> +				'number_of_fragments' => apply_filters( 'ep_highlight_number_of_fragments', 0, $field ),
I added and committed the new comment.

2023-10-04 21:13 UTC, felipeelia commented
Closing in favor of #3681

2023-10-04 21:13 UTC, closed without merging