Add Date block
10up/ElasticPress pull request #3700
Opened 2023-10-17 10:05 UTC by burhandodhy

### Description of the Change

Closes #

### How to test the Change

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability

### Credits

Props @username, @username2, ...

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2023-10-17 14:42 UTC, felipeelia reviewed
@burhandodhy I gave it a quick look and overall it looks good, just added a few comments. Let's also ask @JakePT to give it a look.

2023-10-17 14:42 UTC, felipeelia commented on includes/classes/Feature/Facets/Facets.php
> +		$data = apply_filters( 'ep_facets_script_date', [] );
Is it related to date or data, @burhandodhy?

2023-10-17 14:42 UTC, felipeelia commented on includes/classes/Feature/Facets/Types/Date/FacetType.php
> +		return apply_filters( 'ep_facet_date_options', $options );
It would be great if we could add a code example to this docblock @burhandodhy.

2023-10-18 08:00 UTC, JakePT requested changes

2023-10-18 08:00 UTC, JakePT commented on assets/css/facets.css
> +}
Can we try and match the styles of the other filter blocks a little more?

<img width="336" alt="Screenshot 2023-10-18 at 5 38 14 pm" src="https://github.com/10up/ElasticPress/assets/4100733/d85b4613-b56e-45c3-b9f0-65a72f07894a">

In particular:

 - The colour of the unselected radio button.
 - In the selected state can we include a white dot in the same style as the checkbox:
   <img width="75" alt="Screenshot 2023-10-18 at 5 40 00 pm" src="https://github.com/10up/ElasticPress/assets/4100733/a0f970ba-51d9-4217-8a34-e041a5049644">
 - The size of the radio button and the space between it and the label.
 - The Custom option seems to have an additional space in front of the label.

2023-10-18 08:00 UTC, JakePT commented on assets/js/blocks/facets/date/Edit.js
> +						label={__('Display custom date', 'elasticpress')}
Nitpick, but can we be a little more specific here, eg. "Display custom date option" or "Display custom option"?

2023-10-18 08:00 UTC, JakePT commented on assets/js/blocks/facets/date/index.js
> +import edit from './edit';
It looks like the Edit.js file has been committed with an uppercase E. Can you commit it with the lowercase filename? This might help: https://stackoverflow.com/a/20907647

2023-10-18 08:00 UTC, JakePT commented on package.json
> +      "facets-date-script": "./assets/js/blocks/facets/date/index.js",
Just for consistency with the other blocks, can we call this `facets-date-block-script`?

2023-10-18 08:00 UTC, JakePT commented on assets/js/facets.js
> +const initDateFacet = () => {
Since this is only relevant to the Date block, can we put this in a viewScript, like the Meta Range block?

2023-10-18 08:00 UTC, JakePT commented on includes/classes/Feature/Facets/Types/Date/Renderer.php
> +							<?php esc_html_e( 'Clear', 'elasticpress' ); ?>
Could we lay this out similarly to the Meta Range block, for consistency?

<img width="322" alt="Screenshot 2023-10-18 at 5 51 27 pm" src="https://github.com/10up/ElasticPress/assets/4100733/512efcf9-fae7-43bd-83f5-08b8f70bd478">

Although, in the case of the meta range block the Filter button is always visible, so I'm wondering if it wouldn't be better to have an "all" radio button option, instead of a clear link, since the other list filters don't have one. What do you think @felipeelia?

Also, can we add the `wp-element-button` class to the button, for themes that style this element, and for consistency with the meta range block, which uses it.

2023-10-18 08:00 UTC, JakePT commented on includes/classes/Feature/Facets/Facets.php
> +		wp_localize_script( 'elasticpress-facets', 'epFacets', $data );
If we move the script to its own file, as I suggest elsewhere, we should make this date block specific, like `epDateFacet`.

2023-10-18 08:00 UTC, JakePT commented on assets/js/blocks/facets/date/Edit.js
> +				<PanelBody>
Can we add a "Settings" title here, for consistency with the other filter blocks?

2023-10-18 08:00 UTC, JakePT commented on includes/classes/Feature/Facets/Types/Date/Renderer.php
> +					<form class="facet-date-form <?php echo ! $is_custom_date ? 'hide' : ''; ?>">
Can we prefix our classes with `ep-`. For state classes, can we use `is-hidden`, instead of `hide`.

2023-10-18 08:00 UTC, JakePT commented on includes/classes/Feature/Facets/Types/Date/Renderer.php
> +					<a aria-label="Apply filter: <?php esc_html_e( 'Custom', 'elasticpress' ); ?>" href="#" rel="nofollow" class="ep-date-range-custom <?php echo $is_custom_date ? 'checked' : ''; ?>">
I think this will need some changes for accessibility, only when the filter is not applied:

 - Add `role="button"`
 - Add an `aria-expanded` attribute that changes when the date form is shown.
 - Change the aria-label to something like "Select date range".

When it is already applied it should just be a link and the label should read "Remove filter", like the checkbox filters.

2023-10-18 08:00 UTC, JakePT commented on assets/css/facets.css
> +}
Also, the layout looks a little messed up in Safari:

<img width="311" alt="Screenshot 2023-10-18 at 6 52 21 pm" src="https://github.com/10up/ElasticPress/assets/4100733/833635b5-ef28-4d22-98b1-3f964f01631a">

2023-10-18 08:00 UTC, JakePT commented on includes/classes/Feature/Facets/Types/Date/FacetType.php
> +			$formatted_dates[] = $date->format( 'Y-m-d 00:00:00' );
The "To" date should probably be 23:59:59, otherwise if I filter 2023-01-01 to 2023-01-04 any posts made on the 4th won't be included.

2023-10-18 13:06 UTC, felipeelia commented on includes/classes/Feature/Facets/Types/Date/Renderer.php
> +							<?php esc_html_e( 'Clear', 'elasticpress' ); ?>
the "all" radio button makes more sense, yeah.

2023-10-22 21:13 UTC, felipeelia requested changes
@burhandodhy I gave this a try and if I uncheck the "Display custom date option" and save, the block doesn't seem to work anymore. (I see a `Cannot read properties of null (reading 'classList')` error in the console.)

2023-10-23 16:46 UTC, merged