WIP: Updated Synonyms UI
10up/ElasticPress pull request #3814
Opened 2024-01-17 11:58 UTC by JakePT

### Description of the Change

Closes #

### How to test the Change

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability

### Credits

Props @username, @username2, ...

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2024-03-18 18:24 UTC, felipeelia requested changes

2024-03-18 18:24 UTC, felipeelia commented on includes/classes/Feature/Search/Synonyms.php
> +	 * @since  3.2
Shouldn't this be 5.1.0?

2024-03-18 18:24 UTC, felipeelia commented on includes/classes/REST/Synonyms.php
> + * @since 5.0.0
Shouldn't this be 5.1.0?

2024-04-02 07:49 UTC, JakePT commented on includes/classes/Feature/Search/Synonyms.php
> +	 * @since  3.2
@felipeelia Fixed.

2024-04-02 07:49 UTC, JakePT commented on includes/classes/REST/Synonyms.php
> + * @since 5.0.0
@felipeelia Fixed.

2024-04-12 12:08 UTC, merged